const state = {};

var data = [
      // --- GERAL E INESPECÍFICO ---
    { "id": "41", "Codigo": "A01", "Descricao": "Dor generalizada / múltipla", "Categoria": "Geral e inespecífico" },
    { "id": "42", "Codigo": "A02", "Descricao": "Arrepios / calafrios", "Categoria": "Geral e inespecífico" },
    { "id": "43", "Codigo": "A03", "Descricao": "Febre", "Categoria": "Geral e inespecífico" },
    { "id": "44", "Codigo": "A04", "Descricao": "Debilidade / cansaço geral / fadiga", "Categoria": "Geral e inespecífico" },
    { "id": "45", "Codigo": "A05", "Descricao": "Sentir-se doente", "Categoria": "Geral e inespecífico" },
    { "id": "46", "Codigo": "A06", "Descricao": "Desmaio / síncope", "Categoria": "Geral e inespecífico" },
    { "id": "47", "Codigo": "A07", "Descricao": "Coma", "Categoria": "Geral e inespecífico" },
    { "id": "48", "Codigo": "A08", "Descricao": "Inchaço", "Categoria": "Geral e inespecífico" },
    { "id": "49", "Codigo": "A09", "Descricao": "Problemas de sudorese", "Categoria": "Geral e inespecífico" },
    { "id": "50", "Codigo": "A10", "Descricao": "Sangramento / Hemorragia NE", "Categoria": "Geral e inespecífico" },
    { "id": "51", "Codigo": "A11", "Descricao": "Dores torácicas NE", "Categoria": "Geral e inespecífico" },
    { "id": "52", "Codigo": "A13", "Descricao": "Receio / Medo do tratamento", "Categoria": "Geral e inespecífico" },
    { "id": "53", "Codigo": "A16", "Descricao": "Criança irritável", "Categoria": "Geral e inespecífico" },
    { "id": "54", "Codigo": "A18", "Descricao": "Preocupação com aparência", "Categoria": "Geral e inespecífico" },
    { "id": "55", "Codigo": "A20", "Descricao": "Pedido / discussão eutanásia", "Categoria": "Geral e inespecífico" },
    { "id": "56", "Codigo": "A21", "Descricao": "Fator de risco de malignidade", "Categoria": "Geral e inespecífico" },
    { "id": "57", "Codigo": "A23", "Descricao": "Fator de risco NE", "Categoria": "Geral e inespecífico" },
    { "id": "58", "Codigo": "A25", "Descricao": "Medo de morrer / medo da morte", "Categoria": "Geral e inespecífico" },
    { "id": "59", "Codigo": "A26", "Descricao": "Medo de câncer NE", "Categoria": "Geral e inespecífico" },
    { "id": "60", "Codigo": "A27", "Descricao": "Medo de outra doença NE", "Categoria": "Geral e inespecífico" },
    { "id": "61", "Codigo": "A28", "Descricao": "Limitação funcional / incapacidade NE", "Categoria": "Geral e inespecífico" },
    { "id": "62", "Codigo": "A29", "Descricao": "Outros sinais / sintomas gerais", "Categoria": "Geral e inespecífico" },
    { "id": "1", "Codigo": "A30", "Descricao": "Exame médico / avaliação de saúde completo", "Categoria": "Geral e inespecífico" },
    { "id": "2", "Codigo": "A31", "Descricao": "Exame médico / avaliação de saúde parcial", "Categoria": "Geral e inespecífico" },
    { "id": "3", "Codigo": "A32", "Descricao": "Teste de sensibilidade", "Categoria": "Geral e inespecífico" },
    { "id": "4", "Codigo": "A33", "Descricao": "Exame microbiológico / imunológico", "Categoria": "Geral e inespecífico" },
    { "id": "5", "Codigo": "A34", "Descricao": "Análise de sangue", "Categoria": "Geral e inespecífico" },
    { "id": "6", "Codigo": "A35", "Descricao": "Análise de urina", "Categoria": "Geral e inespecífico" },
    { "id": "7", "Codigo": "A36", "Descricao": "Análise de fezes", "Categoria": "Geral e inespecífico" },
    { "id": "8", "Codigo": "A37", "Descricao": "Citologia esfoliativa / histologia", "Categoria": "Geral e inespecífico" },
    { "id": "9", "Codigo": "A38", "Descricao": "Outras análises laboratoriais NE", "Categoria": "Geral e inespecífico" },
    { "id": "10", "Codigo": "A39", "Descricao": "Teste de função física", "Categoria": "Geral e inespecífico" },
    { "id": "11", "Codigo": "A40", "Descricao": "Endoscopia diagnóstica", "Categoria": "Geral e inespecífico" },
    { "id": "12", "Codigo": "A41", "Descricao": "Radiologia diagnóstica", "Categoria": "Geral e inespecífico" },
    { "id": "13", "Codigo": "A42", "Descricao": "Eletrocardiograma", "Categoria": "Geral e inespecífico" },
    { "id": "14", "Codigo": "A43", "Descricao": "Outros procedimentos diagnósticos", "Categoria": "Geral e inespecífico" },
    { "id": "15", "Codigo": "A44", "Descricao": "Vacinação / medicação preventiva", "Categoria": "Geral e inespecífico" },
    { "id": "16", "Codigo": "A45", "Descricao": "Educação em saúde / aconselhamento / dieta", "Categoria": "Geral e inespecífico" },
    { "id": "17", "Codigo": "A46", "Descricao": "Consulta com profissional de APS", "Categoria": "Geral e inespecífico" },
    { "id": "18", "Codigo": "A47", "Descricao": "Consulta com especialista", "Categoria": "Geral e inespecífico" },
    { "id": "19", "Codigo": "A48", "Descricao": "Esclarecimento / discussão do motivo da consulta", "Categoria": "Geral e inespecífico" },
    { "id": "20", "Codigo": "A49", "Descricao": "Outros procedimentos preventivos", "Categoria": "Geral e inespecífico" },
    { "id": "21", "Codigo": "A50", "Descricao": "Medicação / prescrição / renovação / injeção", "Categoria": "Geral e inespecífico" },
    { "id": "22", "Codigo": "A51", "Descricao": "Incisão / drenagem / aspiração / remoção", "Categoria": "Geral e inespecífico" },
    { "id": "23", "Codigo": "A52", "Descricao": "Excisão / biópsia / remoção / debridamento / cauterização", "Categoria": "Geral e inespecífico" },
    { "id": "24", "Codigo": "A53", "Descricao": "Cateterização / intubação", "Categoria": "Geral e inespecífico" },
    { "id": "25", "Codigo": "A54", "Descricao": "Reparação / sutura / gesso / prótese", "Categoria": "Geral e inespecífico" },
    { "id": "26", "Codigo": "A55", "Descricao": "Injeção local / infiltração", "Categoria": "Geral e inespecífico" },
    { "id": "27", "Codigo": "A56", "Descricao": "Ligadura / compressa / tamponamento", "Categoria": "Geral e inespecífico" },
    { "id": "28", "Codigo": "A57", "Descricao": "Medicina física / reabilitação", "Categoria": "Geral e inespecífico" },
    { "id": "29", "Codigo": "A58", "Descricao": "Aconselhamento / escuta terapêutica", "Categoria": "Geral e inespecífico" },
    { "id": "30", "Codigo": "A59", "Descricao": "Outros procedimentos terapêuticos / pequena cirurgia NE", "Categoria": "Geral e inespecífico" },
    { "id": "31", "Codigo": "A60", "Descricao": "Resultados de análises / procedimentos", "Categoria": "Geral e inespecífico" },
    { "id": "32", "Codigo": "A61", "Descricao": "Contra-referência de outro prestador - resultado de exames", "Categoria": "Geral e inespecífico" },
    { "id": "33", "Codigo": "A62", "Descricao": "Procedimento administrativo", "Categoria": "Geral e inespecífico" },
    { "id": "34", "Codigo": "A63", "Descricao": "Consulta de seguimento não especificada", "Categoria": "Geral e inespecífico" },
    { "id": "35", "Codigo": "A64", "Descricao": "Episódio / problema iniciado pelo prestador", "Categoria": "Geral e inespecífico" },
    { "id": "36", "Codigo": "A65", "Descricao": "Episódio / problema iniciado por outro NE", "Categoria": "Geral e inespecífico" },
    { "id": "37", "Codigo": "A66", "Descricao": "Referenciado a outro prestador / enfermeiro / assistente social", "Categoria": "Geral e inespecífico" },
    { "id": "38", "Codigo": "A67", "Descricao": "Referenciado para médico / especialista / clínica / hospital", "Categoria": "Geral e inespecífico" },
    { "id": "39", "Codigo": "A68", "Descricao": "Outras referenciações NE", "Categoria": "Geral e inespecífico" },
    { "id": "40", "Codigo": "A69", "Descricao": "Outro motivo de consulta NE", "Categoria": "Geral e inespecífico" },
    { "id": "63", "Codigo": "A70", "Descricao": "Tuberculose", "Categoria": "Geral e inespecífico" },
    { "id": "64", "Codigo": "A71", "Descricao": "Sarampo", "Categoria": "Geral e inespecífico" },
    { "id": "65", "Codigo": "A72", "Descricao": "Varicela", "Categoria": "Geral e inespecífico" },
    { "id": "66", "Codigo": "A73", "Descricao": "Malária", "Categoria": "Geral e inespecífico" },
    { "id": "67", "Codigo": "A74", "Descricao": "Rubéola", "Categoria": "Geral e inespecífico" },
    { "id": "68", "Codigo": "A75", "Descricao": "Mononucleose infecciosa", "Categoria": "Geral e inespecífico" },
    { "id": "69", "Codigo": "A76", "Descricao": "Outro exantema viral", "Categoria": "Geral e inespecífico" },
    { "id": "70", "Codigo": "A77", "Descricao": "Dengue e outras doenças virais NE", "Categoria": "Geral e inespecífico" },
    { "id": "71", "Codigo": "A78", "Descricao": "Hanseníase e outras doenças infecciosas NE", "Categoria": "Geral e inespecífico" },
    { "id": "72", "Codigo": "A79", "Descricao": "Carcinomatose (localização primária desconhecida)", "Categoria": "Geral e inespecífico" },
    { "id": "73", "Codigo": "A80", "Descricao": "Lesão traumática / acidente NE", "Categoria": "Geral e inespecífico" },
    { "id": "74", "Codigo": "A81", "Descricao": "Politraumatismos / ferimentos múltiplos", "Categoria": "Geral e inespecífico" },
    { "id": "75", "Codigo": "A82", "Descricao": "Efeito secundário de lesão traumática", "Categoria": "Geral e inespecífico" },
    { "id": "76", "Codigo": "A84", "Descricao": "Intoxicação por medicamento", "Categoria": "Geral e inespecífico" },
    { "id": "77", "Codigo": "A85", "Descricao": "Efeito adverso de fármaco dose correta", "Categoria": "Geral e inespecífico" },
    { "id": "78", "Codigo": "A86", "Descricao": "Efeito tóxico de substância não medicinal", "Categoria": "Geral e inespecífico" },
    { "id": "79", "Codigo": "A87", "Descricao": "Complicações de tratamento médico", "Categoria": "Geral e inespecífico" },
    { "id": "80", "Codigo": "A88", "Descricao": "Efeito adverso de fator físico", "Categoria": "Geral e inespecífico" },
    { "id": "81", "Codigo": "A89", "Descricao": "Efeito da prótese", "Categoria": "Geral e inespecífico" },
    { "id": "82", "Codigo": "A90", "Descricao": "Malformação congénita NE / múltiplas", "Categoria": "Geral e inespecífico" },
    { "id": "83", "Codigo": "A91", "Descricao": "Investigação com resultado anormal NE", "Categoria": "Geral e inespecífico" },
    { "id": "84", "Codigo": "A92", "Descricao": "Alergia / reação alérgica NE", "Categoria": "Geral e inespecífico" },
    { "id": "85", "Codigo": "A93", "Descricao": "Recém nascido prematuro", "Categoria": "Geral e inespecífico" },
    { "id": "86", "Codigo": "A94", "Descricao": "Morbidade perinatal, outra", "Categoria": "Geral e inespecífico" },
    { "id": "87", "Codigo": "A95", "Descricao": "Mortalidade perinatal", "Categoria": "Geral e inespecífico" },
    { "id": "88", "Codigo": "A96", "Descricao": "Morte", "Categoria": "Geral e inespecífico" },
    { "id": "89", "Codigo": "A97", "Descricao": "Sem doença", "Categoria": "Geral e inespecífico" },
    { "id": "90", "Codigo": "A98", "Descricao": "Medicina preventiva / manutenção da saúde", "Categoria": "Geral e inespecífico" },
    { "id": "91", "Codigo": "A99", "Descricao": "Outras doenças gerais NE", "Categoria": "Geral e inespecífico" },

    // --- SANGUE, SISTEMA HEMATOPOIÉTICO, LINFÁTICO E BAÇO ---
    { "id": "92", "Codigo": "B02", "Descricao": "Gânglio linfático aumentado / doloroso", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "93", "Codigo": "B04", "Descricao": "Sinais / sintomas sangue", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "94", "Codigo": "B25", "Descricao": "Medo de VIH / HIV / SIDA / AIDS", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "95", "Codigo": "B26", "Descricao": "Medo de câncer no sangue / linfático", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "96", "Codigo": "B27", "Descricao": "Medo de outras doenças do sangue / vasos linfáticos", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "97", "Codigo": "B28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "98", "Codigo": "B29", "Descricao": "Outros sinais sintomas do sangue / sistema linfático / baço NE", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "41", "Codigo": "B33", "Descricao": "Exame microbiológico / imunológico do sangue", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "42", "Codigo": "B34", "Descricao": "Análise de sangue (Hemograma, coagulograma, etc.)", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "43", "Codigo": "B50", "Descricao": "Prescrição de medicação para sistema hematopoiético", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "44", "Codigo": "B67", "Descricao": "Encaminhamento para hematologista", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "99", "Codigo": "B70", "Descricao": "Linfadenite aguda", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "100", "Codigo": "B71", "Descricao": "Linfadenite crónica NE", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "101", "Codigo": "B72", "Descricao": "Doença de Hodgkin / linfomas", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "102", "Codigo": "B73", "Descricao": "Leucemia", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "103", "Codigo": "B74", "Descricao": "Outra neoplasia maligna no sangue", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "104", "Codigo": "B75", "Descricao": "Neoplasia benigna NE", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "105", "Codigo": "B76", "Descricao": "Rotura traumática do baço", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "106", "Codigo": "B77", "Descricao": "Outras lesões traumáticas do sangue / linfa / baço", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "107", "Codigo": "B78", "Descricao": "Anemia hemolítica hereditária", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "108", "Codigo": "B79", "Descricao": "Outra malformação congénita do sangue linfática", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "109", "Codigo": "B80", "Descricao": "Anemia por deficiência ferro", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "110", "Codigo": "B81", "Descricao": "Anemia perniciosa / deficiência de folatos", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "111", "Codigo": "B82", "Descricao": "Outras anemias NE", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "112", "Codigo": "B83", "Descricao": "Púrpura / defeitos de coagulação", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "113", "Codigo": "B84", "Descricao": "Glóbulos brancos anormais", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "114", "Codigo": "B87", "Descricao": "Esplenomegalia", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "115", "Codigo": "B90", "Descricao": "Infecção por VIH / HIV / SIDA / AIDS", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },
    { "id": "116", "Codigo": "B99", "Descricao": "Outra doença do sangue / linfáticos / baço", "Categoria": "Sangue, sistema hematopoiético, linfático e baço" },

    // --- DIGESTIVO ---
    { "id": "117", "Codigo": "D01", "Descricao": "Dor abdominal generalizada / cólicas", "Categoria": "Digestivo" },
    { "id": "118", "Codigo": "D02", "Descricao": "Dores abdominais, epigástricas", "Categoria": "Digestivo" },
    { "id": "119", "Codigo": "D03", "Descricao": "Azia / Queimação", "Categoria": "Digestivo" },
    { "id": "120", "Codigo": "D04", "Descricao": "Dor anal / rectal", "Categoria": "Digestivo" },
    { "id": "121", "Codigo": "D05", "Descricao": "Irritação perianal", "Categoria": "Digestivo" },
    { "id": "122", "Codigo": "D06", "Descricao": "Outras dores abdominais localizadas", "Categoria": "Digestivo" },
    { "id": "123", "Codigo": "D07", "Descricao": "Dispepsia / indigestão", "Categoria": "Digestivo" },
    { "id": "124", "Codigo": "D08", "Descricao": "Flatulência / gases / eructações", "Categoria": "Digestivo" },
    { "id": "125", "Codigo": "D09", "Descricao": "Náusea", "Categoria": "Digestivo" },
    { "id": "126", "Codigo": "D10", "Descricao": "Vómito", "Categoria": "Digestivo" },
    { "id": "127", "Codigo": "D11", "Descricao": "Diarreia", "Categoria": "Digestivo" },
    { "id": "128", "Codigo": "D12", "Descricao": "Obstipação", "Categoria": "Digestivo" },
    { "id": "129", "Codigo": "D13", "Descricao": "Icterícia", "Categoria": "Digestivo" },
    { "id": "130", "Codigo": "D14", "Descricao": "Hematemese / vómito sangue", "Categoria": "Digestivo" },
    { "id": "131", "Codigo": "D15", "Descricao": "Melena", "Categoria": "Digestivo" },
    { "id": "132", "Codigo": "D16", "Descricao": "Hemorragia retal", "Categoria": "Digestivo" },
    { "id": "133", "Codigo": "D17", "Descricao": "Incontinência fecal", "Categoria": "Digestivo" },
    { "id": "134", "Codigo": "D18", "Descricao": "Alterações nas fezes / mov. intestinais", "Categoria": "Digestivo" },
    { "id": "135", "Codigo": "D19", "Descricao": "Sinais / sintomas dos dentes / gengivas", "Categoria": "Digestivo" },
    { "id": "136", "Codigo": "D20", "Descricao": "Sinais / sintomas da boca / língua / lábios", "Categoria": "Digestivo" },
    { "id": "137", "Codigo": "D21", "Descricao": "Problemas de deglutição", "Categoria": "Digestivo" },
    { "id": "138", "Codigo": "D23", "Descricao": "Hepatomegalia", "Categoria": "Digestivo" },
    { "id": "139", "Codigo": "D24", "Descricao": "Massa abdominal NE", "Categoria": "Digestivo" },
    { "id": "140", "Codigo": "D25", "Descricao": "Distensão abdominal", "Categoria": "Digestivo" },
    { "id": "141", "Codigo": "D26", "Descricao": "Medo de câncer no aparelho digestivo", "Categoria": "Digestivo" },
    { "id": "142", "Codigo": "D27", "Descricao": "Medo de outras doenças aparelho digestivo", "Categoria": "Digestivo" },
    { "id": "143", "Codigo": "D28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Digestivo" },
    { "id": "144", "Codigo": "D29", "Descricao": "Outros sinais / sintomas digestivos", "Categoria": "Digestivo" },
    { "id": "45", "Codigo": "D36", "Descricao": "Análise de fezes (Parasitológico, sangue oculto)", "Categoria": "Digestivo" },
    { "id": "46", "Codigo": "D37", "Descricao": "Citologia esfoliativa / histologia do trato digestivo", "Categoria": "Digestivo" },
    { "id": "47", "Codigo": "D40", "Descricao": "Endoscopia diagnóstica (EDA / colonoscopia)", "Categoria": "Digestivo" },
    { "id": "48", "Codigo": "D50", "Descricao": "Prescrição de medicação para aparelho digestivo", "Categoria": "Digestivo" },
    { "id": "145", "Codigo": "D70", "Descricao": "Infecção gastrointestinal", "Categoria": "Digestivo" },
    { "id": "146", "Codigo": "D71", "Descricao": "Caxumba / parotidite epidémica", "Categoria": "Digestivo" },
    { "id": "147", "Codigo": "D72", "Descricao": "Hepatite viral", "Categoria": "Digestivo" },
    { "id": "148", "Codigo": "D73", "Descricao": "Gastroenterite, presumível infecção", "Categoria": "Digestivo" },
    { "id": "149", "Codigo": "D74", "Descricao": "Neoplasia maligna do estômago", "Categoria": "Digestivo" },
    { "id": "150", "Codigo": "D75", "Descricao": "Neoplasia maligna do cólon / reto", "Categoria": "Digestivo" },
    { "id": "151", "Codigo": "D76", "Descricao": "Neoplasia maligna do pâncreas", "Categoria": "Digestivo" },
    { "id": "152", "Codigo": "D77", "Descricao": "Neoplasia maligna do aparelho digestivo NE", "Categoria": "Digestivo" },
    { "id": "153", "Codigo": "D78", "Descricao": "Neoplasia benigna do aparelho digestivo / incerta", "Categoria": "Digestivo" },
    { "id": "154", "Codigo": "D79", "Descricao": "Corpo estranho no aparelho digestivo", "Categoria": "Digestivo" },
    { "id": "155", "Codigo": "D80", "Descricao": "Outras lesões traumáticas", "Categoria": "Digestivo" },
    { "id": "156", "Codigo": "D81", "Descricao": "Malformações congénitas do aparelho digestivo", "Categoria": "Digestivo" },
    { "id": "157", "Codigo": "D82", "Descricao": "Doença dos dentes / gengivas", "Categoria": "Digestivo" },
    { "id": "158", "Codigo": "D83", "Descricao": "Doença da boca / língua / lábios", "Categoria": "Digestivo" },
    { "id": "159", "Codigo": "D84", "Descricao": "Doença do esófago", "Categoria": "Digestivo" },
    { "id": "160", "Codigo": "D85", "Descricao": "Úlcera do duodeno", "Categoria": "Digestivo" },
    { "id": "161", "Codigo": "D86", "Descricao": "Úlcera péptica, outra", "Categoria": "Digestivo" },
    { "id": "162", "Codigo": "D87", "Descricao": "Alterações funcionais estômago", "Categoria": "Digestivo" },
    { "id": "163", "Codigo": "D88", "Descricao": "Apendicite", "Categoria": "Digestivo" },
    { "id": "164", "Codigo": "D89", "Descricao": "Hérnia inguinal", "Categoria": "Digestivo" },
    { "id": "165", "Codigo": "D90", "Descricao": "Hérnia de hiato / diafragmática", "Categoria": "Digestivo" },
    { "id": "166", "Codigo": "D91", "Descricao": "Hérnia abdominal outras", "Categoria": "Digestivo" },
    { "id": "167", "Codigo": "D92", "Descricao": "Doença diverticular intestinal", "Categoria": "Digestivo" },
    { "id": "168", "Codigo": "D93", "Descricao": "Síndrome do cólon irritável", "Categoria": "Digestivo" },
    { "id": "169", "Codigo": "D94", "Descricao": "Enterite crónica / colite ulcerosa", "Categoria": "Digestivo" },
    { "id": "170", "Codigo": "D95", "Descricao": "Fissura anal / abcesso perianal", "Categoria": "Digestivo" },
    { "id": "171", "Codigo": "D96", "Descricao": "Lombrigas / outros parasitas", "Categoria": "Digestivo" },
    { "id": "172", "Codigo": "D97", "Descricao": "Doenças de fígado NE", "Categoria": "Digestivo" },
    { "id": "173", "Codigo": "D98", "Descricao": "Colecistite, colelitíase", "Categoria": "Digestivo" },
    { "id": "174", "Codigo": "D99", "Descricao": "Outra doença do aparelho digestivo", "Categoria": "Digestivo" },

    // --- OLHO ---
    { "id": "175", "Codigo": "F01", "Descricao": "Dor no olho", "Categoria": "Olho" },
    { "id": "176", "Codigo": "F02", "Descricao": "Olho vermelho", "Categoria": "Olho" },
    { "id": "177", "Codigo": "F03", "Descricao": "Secreção ocular", "Categoria": "Olho" },
    { "id": "178", "Codigo": "F04", "Descricao": "Moscas volantes / pontos luminosos / escotomas / manchas", "Categoria": "Olho" },
    { "id": "179", "Codigo": "F05", "Descricao": "Outras perturbações visuais", "Categoria": "Olho" },
    { "id": "180", "Codigo": "F13", "Descricao": "Sensações oculares anormais", "Categoria": "Olho" },
    { "id": "181", "Codigo": "F14", "Descricao": "Movimentos oculares anormais", "Categoria": "Olho" },
    { "id": "182", "Codigo": "F15", "Descricao": "Aparência anormal nos olhos", "Categoria": "Olho" },
    { "id": "183", "Codigo": "F16", "Descricao": "Sinais / sintomas das pálpebras", "Categoria": "Olho" },
    { "id": "184", "Codigo": "F17", "Descricao": "Sinais / sintomas relacionados a óculos", "Categoria": "Olho" },
    { "id": "185", "Codigo": "F18", "Descricao": "Sinais / sintomas relacionados a lentes de contato", "Categoria": "Olho" },
    { "id": "186", "Codigo": "F27", "Descricao": "Medo de doença ocular", "Categoria": "Olho" },
    { "id": "187", "Codigo": "F28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Olho" },
    { "id": "188", "Codigo": "F29", "Descricao": "Outros sinais / sintomas oculares", "Categoria": "Olho" },
    { "id": "49", "Codigo": "F31", "Descricao": "Exame / avaliação de saúde parcial do olho", "Categoria": "Olho" },
    { "id": "50", "Codigo": "F39", "Descricao": "Teste de função física (Acuidade visual, tonometria)", "Categoria": "Olho" },
    { "id": "51", "Codigo": "F51", "Descricao": "Incisão / drenagem / remoção de corpo estranho ocular", "Categoria": "Olho" },
    { "id": "52", "Codigo": "F67", "Descricao": "Encaminhamento para oftalmologista", "Categoria": "Olho" },
    { "id": "189", "Codigo": "F70", "Descricao": "Conjuntivite infecciosa", "Categoria": "Olho" },
    { "id": "190", "Codigo": "F71", "Descricao": "Conjuntivite alérgica", "Categoria": "Olho" },
    { "id": "191", "Codigo": "F72", "Descricao": "Blefarite / hordéolo / calázio", "Categoria": "Olho" },
    { "id": "192", "Codigo": "F73", "Descricao": "Outras infecções / inflamações oculares", "Categoria": "Olho" },
    { "id": "193", "Codigo": "F74", "Descricao": "Neoplasia do olho / anexos", "Categoria": "Olho" },
    { "id": "194", "Codigo": "F75", "Descricao": "Contusão / hemorragia ocular", "Categoria": "Olho" },
    { "id": "195", "Codigo": "F76", "Descricao": "Corpo estranho ocular", "Categoria": "Olho" },
    { "id": "196", "Codigo": "F79", "Descricao": "Outras lesões traumáticas oculares", "Categoria": "Olho" },
    { "id": "197", "Codigo": "F80", "Descricao": "Obstrução canal lacrimal da criança", "Categoria": "Olho" },
    { "id": "198", "Codigo": "F81", "Descricao": "Outras malformações congénitas do olho", "Categoria": "Olho" },
    { "id": "199", "Codigo": "F82", "Descricao": "Descolamento da retina", "Categoria": "Olho" },
    { "id": "200", "Codigo": "F83", "Descricao": "Retinopatia", "Categoria": "Olho" },
    { "id": "201", "Codigo": "F84", "Descricao": "Degeneração macular", "Categoria": "Olho" },
    { "id": "202", "Codigo": "F85", "Descricao": "Úlcera da córnea", "Categoria": "Olho" },
    { "id": "203", "Codigo": "F86", "Descricao": "Tracoma", "Categoria": "Olho" },
    { "id": "204", "Codigo": "F91", "Descricao": "Erro de refração", "Categoria": "Olho" },
    { "id": "205", "Codigo": "F92", "Descricao": "Catarata", "Categoria": "Olho" },
    { "id": "206", "Codigo": "F93", "Descricao": "Glaucoma", "Categoria": "Olho" },
    { "id": "207", "Codigo": "F94", "Descricao": "Cegueira", "Categoria": "Olho" },
    { "id": "208", "Codigo": "F95", "Descricao": "Estrabismo", "Categoria": "Olho" },
    { "id": "209", "Codigo": "F99", "Descricao": "Outras doenças oculares / anexos", "Categoria": "Olho" },

    // --- OUVIDO ---
    { "id": "210", "Codigo": "H01", "Descricao": "Dor de ouvidos", "Categoria": "Ouvido" },
    { "id": "211", "Codigo": "H02", "Descricao": "Problemas de audição", "Categoria": "Ouvido" },
    { "id": "212", "Codigo": "H03", "Descricao": "Acufeno, zumbidos, ruído, assobios", "Categoria": "Ouvido" },
    { "id": "213", "Codigo": "H04", "Descricao": "Secreção no ouvido", "Categoria": "Ouvido" },
    { "id": "214", "Codigo": "H05", "Descricao": "Hemorragia no ouvido", "Categoria": "Ouvido" },
    { "id": "215", "Codigo": "H13", "Descricao": "Sensação de ouvido tapado", "Categoria": "Ouvido" },
    { "id": "216", "Codigo": "H15", "Descricao": "Preocupação com a aparência das orelhas", "Categoria": "Ouvido" },
    { "id": "217", "Codigo": "H27", "Descricao": "Medo de doença do ouvido", "Categoria": "Ouvido" },
    { "id": "218", "Codigo": "H28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Ouvido" },
    { "id": "219", "Codigo": "H29", "Descricao": "Outros sinais / sintomas ouvido", "Categoria": "Ouvido" },
    { "id": "53", "Codigo": "H31", "Descricao": "Exame físico parcial do ouvido (Otoscopia)", "Categoria": "Ouvido" },
    { "id": "54", "Codigo": "H39", "Descricao": "Teste de função auditiva (Audiometria)", "Categoria": "Ouvido" },
    { "id": "55", "Codigo": "H51", "Descricao": "Remoção de cerúmen / corpo estranho do ouvido", "Categoria": "Ouvido" },
    { "id": "56", "Codigo": "H67", "Descricao": "Encaminhamento para otorrinolaringologista", "Categoria": "Ouvido" },
    { "id": "220", "Codigo": "H70", "Descricao": "Otite externa", "Categoria": "Ouvido" },
    { "id": "221", "Codigo": "H71", "Descricao": "Otite média aguda / miringite", "Categoria": "Ouvido" },
    { "id": "222", "Codigo": "H72", "Descricao": "Otite média serosa", "Categoria": "Ouvido" },
    { "id": "223", "Codigo": "H73", "Descricao": "Infecção da Trompa de Eustáquio", "Categoria": "Ouvido" },
    { "id": "224", "Codigo": "H74", "Descricao": "Otite média crónica", "Categoria": "Ouvido" },
    { "id": "225", "Codigo": "H75", "Descricao": "Neoplasia do ouvido", "Categoria": "Ouvido" },
    { "id": "226", "Codigo": "H76", "Descricao": "Corpo estranho do ouvido", "Categoria": "Ouvido" },
    { "id": "227", "Codigo": "H77", "Descricao": "Perfuração do tímpano", "Categoria": "Ouvido" },
    { "id": "228", "Codigo": "H78", "Descricao": "Traumatismo superficial do ouvido", "Categoria": "Ouvido" },
    { "id": "229", "Codigo": "H79", "Descricao": "Outros traumatismos do ouvido", "Categoria": "Ouvido" },
    { "id": "230", "Codigo": "H80", "Descricao": "Malformações congénitas do ouvido", "Categoria": "Ouvido" },
    { "id": "231", "Codigo": "H81", "Descricao": "Cerúmen devido em excesso", "Categoria": "Ouvido" },
    { "id": "232", "Codigo": "H82", "Descricao": "Síndrome vertiginosa", "Categoria": "Ouvido" },
    { "id": "233", "Codigo": "H83", "Descricao": "Otoesclerose", "Categoria": "Ouvido" },
    { "id": "234", "Codigo": "H84", "Descricao": "Presbiacusia", "Categoria": "Ouvido" },
    { "id": "235", "Codigo": "H85", "Descricao": "Lesão acústica", "Categoria": "Ouvido" },
    { "id": "236", "Codigo": "H86", "Descricao": "Surdez", "Categoria": "Ouvido" },
    { "id": "237", "Codigo": "H99", "Descricao": "Outra doença do ouvido / mastóide", "Categoria": "Ouvido" },

    // --- CIRCULATÓRIO ---
    { "id": "238", "Codigo": "K01", "Descricao": "Dor atribuída ao coração", "Categoria": "Circulatório" },
    { "id": "239", "Codigo": "K02", "Descricao": "Sensação de pressão / aperto atribuída ao coração", "Categoria": "Circulatório" },
    { "id": "240", "Codigo": "K03", "Descricao": "Dores atribuídas ao aparelho circulatório NE", "Categoria": "Circulatório" },
    { "id": "241", "Codigo": "K04", "Descricao": "Palpitações / percepção dos batimentos cardíacos", "Categoria": "Circulatório" },
    { "id": "242", "Codigo": "K05", "Descricao": "Outras irregularidades dos batimentos cardíacos", "Categoria": "Circulatório" },
    { "id": "243", "Codigo": "K06", "Descricao": "Veias proeminentes", "Categoria": "Circulatório" },
    { "id": "244", "Codigo": "K07", "Descricao": "Tornozelos inchados / edema", "Categoria": "Circulatório" },
    { "id": "245", "Codigo": "K22", "Descricao": "Fator de risco para doença cardiovascular", "Categoria": "Circulatório" },
    { "id": "246", "Codigo": "K24", "Descricao": "Medo de doença cardíaca", "Categoria": "Circulatório" },
    { "id": "247", "Codigo": "K25", "Descricao": "Medo de hipertensão", "Categoria": "Circulatório" },
    { "id": "248", "Codigo": "K27", "Descricao": "Medo de outra doença cardiovascular", "Categoria": "Circulatório" },
    { "id": "249", "Codigo": "K28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Circulatório" },
    { "id": "250", "Codigo": "K29", "Descricao": "Outros sinais / sintomas cardiovasculares", "Categoria": "Circulatório" },
    { "id": "57", "Codigo": "K41", "Descricao": "Radiologia diagnóstica cardiovascular", "Categoria": "Circulatório" },
    { "id": "58", "Codigo": "K42", "Descricao": "Eletrocardiograma (ECG)", "Categoria": "Circulatório" },
    { "id": "59", "Codigo": "K45", "Descricao": "Aconselhamento / dieta para sistema cardiovascular", "Categoria": "Circulatório" },
    { "id": "60", "Codigo": "K50", "Descricao": "Prescrição de medicação anti-hipertensiva / cardíaca", "Categoria": "Circulatório" },
    { "id": "251", "Codigo": "K70", "Descricao": "Doença infecciosa do aparelho circulatório", "Categoria": "Circulatório" },
    { "id": "252", "Codigo": "K71", "Descricao": "Febre reumática / cardiopatia", "Categoria": "Circulatório" },
    { "id": "253", "Codigo": "K72", "Descricao": "Neoplasia do aparelho circulatório", "Categoria": "Circulatório" },
    { "id": "254", "Codigo": "K73", "Descricao": "Malformações congénitas do aparelho circulatório", "Categoria": "Circulatório" },
    { "id": "255", "Codigo": "K74", "Descricao": "Doença cardíaca isquémica com angina", "Categoria": "Circulatório" },
    { "id": "256", "Codigo": "K75", "Descricao": "Infarto ou Enfarte agudo do miocárdio", "Categoria": "Circulatório" },
    { "id": "257", "Codigo": "K76", "Descricao": "Doença cardíaca isquémica sem angina", "Categoria": "Circulatório" },
    { "id": "258", "Codigo": "K77", "Descricao": "Insuficiência cardíaca", "Categoria": "Circulatório" },
    { "id": "259", "Codigo": "K78", "Descricao": "Fibrilação / Flutter auricular / atrial", "Categoria": "Circulatório" },
    { "id": "260", "Codigo": "K79", "Descricao": "Taquicardia Paroxística", "Categoria": "Circulatório" },
    { "id": "261", "Codigo": "K80", "Descricao": "Arritmia cardíaca NE", "Categoria": "Circulatório" },
    { "id": "262", "Codigo": "K81", "Descricao": "Sopro cardíaco / arterial NE", "Categoria": "Circulatório" },
    { "id": "263", "Codigo": "K82", "Descricao": "Doença cardiopulmonar", "Categoria": "Circulatório" },
    { "id": "264", "Codigo": "K83", "Descricao": "Doença valvular cardíaca NE", "Categoria": "Circulatório" },
    { "id": "265", "Codigo": "K84", "Descricao": "Outras doenças cardíacas", "Categoria": "Circulatório" },
    { "id": "266", "Codigo": "K85", "Descricao": "Pressão arterial elevada", "Categoria": "Circulatório" },
    { "id": "267", "Codigo": "K86", "Descricao": "Hipertensão sem complicações", "Categoria": "Circulatório" },
    { "id": "268", "Codigo": "K87", "Descricao": "Hipertensão com complicações", "Categoria": "Circulatório" },
    { "id": "269", "Codigo": "K88", "Descricao": "Hipotensão postural", "Categoria": "Circulatório" },
    { "id": "270", "Codigo": "K89", "Descricao": "Isquémia / acidente cerebral transitório(o)", "Categoria": "Circulatório" },
    { "id": "271", "Codigo": "K90", "Descricao": "Trombose / acidente vascular cerebral (AVC)", "Categoria": "Circulatório" },
    { "id": "272", "Codigo": "K91", "Descricao": "Doença vascular cerebral", "Categoria": "Circulatório" },
    { "id": "273", "Codigo": "K92", "Descricao": "Aterosclerose / doença vascular periférica", "Categoria": "Circulatório" },
    { "id": "274", "Codigo": "K93", "Descricao": "Embolia pulmonar", "Categoria": "Circulatório" },
    { "id": "275", "Codigo": "K94", "Descricao": "Flebite / tromboflebite", "Categoria": "Circulatório" },
    { "id": "276", "Codigo": "K95", "Descricao": "Veias varicosas da perna", "Categoria": "Circulatório" },
    { "id": "277", "Codigo": "K96", "Descricao": "Hemorroidas", "Categoria": "Circulatório" },
    { "id": "278", "Codigo": "K99", "Descricao": "Outras doenças do aparelho circulatório", "Categoria": "Circulatório" },

    // --- MÚSCULO-ESQUELÉTICO ---
    { "id": "279", "Codigo": "L01", "Descricao": "Sinais / sintomas do pescoço", "Categoria": "Músculo-esquelético" },
    { "id": "280", "Codigo": "L02", "Descricao": "Sinais / sintomas da região dorsal", "Categoria": "Músculo-esquelético" },
    { "id": "281", "Codigo": "L03", "Descricao": "Sinais / sintomas da região lombar", "Categoria": "Músculo-esquelético" },
    { "id": "282", "Codigo": "L04", "Descricao": "Sinais / sintomas do tórax", "Categoria": "Músculo-esquelético" },
    { "id": "283", "Codigo": "L05", "Descricao": "Sinais / sintomas da axila", "Categoria": "Músculo-esquelético" },
    { "id": "284", "Codigo": "L07", "Descricao": "Sinais / sintomas da mandíbula", "Categoria": "Músculo-esquelético" },
    { "id": "285", "Codigo": "L08", "Descricao": "Sinais / sintomas dos ombros", "Categoria": "Músculo-esquelético" },
    { "id": "286", "Codigo": "L09", "Descricao": "Sinais / sintomas dos braços", "Categoria": "Músculo-esquelético" },
    { "id": "287", "Codigo": "L10", "Descricao": "Sinais / sintomas dos cotovelos", "Categoria": "Músculo-esquelético" },
    { "id": "288", "Codigo": "L11", "Descricao": "Sinais / sintomas dos punhos", "Categoria": "Músculo-esquelético" },
    { "id": "289", "Codigo": "L12", "Descricao": "Sinais / sintomas das mãos e dedos", "Categoria": "Músculo-esquelético" },
    { "id": "290", "Codigo": "L13", "Descricao": "Sinais / sintomas do quadril", "Categoria": "Músculo-esquelético" },
    { "id": "291", "Codigo": "L14", "Descricao": "Sinais / sintomas da coxa / perna", "Categoria": "Músculo-esquelético" },
    { "id": "292", "Codigo": "L15", "Descricao": "Sinais / sintomas do joelho", "Categoria": "Músculo-esquelético" },
    { "id": "293", "Codigo": "L16", "Descricao": "Sinais / sintomas do tornozelo", "Categoria": "Músculo-esquelético" },
    { "id": "294", "Codigo": "L17", "Descricao": "Sinais / sintomas do pé / dedos pé", "Categoria": "Músculo-esquelético" },
    { "id": "295", "Codigo": "L18", "Descricao": "Dores musculares", "Categoria": "Músculo-esquelético" },
    { "id": "296", "Codigo": "L19", "Descricao": "Sinais / sintomas musculares NE", "Categoria": "Músculo-esquelético" },
    { "id": "297", "Codigo": "L20", "Descricao": "Sinais / sintomas das articulações NE", "Categoria": "Músculo-esquelético" },
    { "id": "298", "Codigo": "L26", "Descricao": "Medo de câncer no aparelho músculo-esquelético", "Categoria": "Músculo-esquelético" },
    { "id": "299", "Codigo": "L27", "Descricao": "Medo de doença no aparelho músculo-esquelético, outro", "Categoria": "Músculo-esquelético" },
    { "id": "300", "Codigo": "L28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Músculo-esquelético" },
    { "id": "301", "Codigo": "L29", "Descricao": "Outros sinais / sintomas do aparelho músculo-esquelético", "Categoria": "Músculo-esquelético" },
    { "id": "61", "Codigo": "L41", "Descricao": "Radiologia diagnóstica do sistema músculo-esquelético", "Categoria": "Músculo-esquelético" },
    { "id": "62", "Codigo": "L54", "Descricao": "Reparação / gesso / órtese", "Categoria": "Músculo-esquelético" },
    { "id": "63", "Codigo": "L55", "Descricao": "Injeção local / infiltração articular", "Categoria": "Músculo-esquelético" },
    { "id": "64", "Codigo": "L57", "Descricao": "Medicina física / reabilitação (Fisioterapia)", "Categoria": "Músculo-esquelético" },
    { "id": "302", "Codigo": "L70", "Descricao": "Infecções do aparelho músculo-esquelético", "Categoria": "Músculo-esquelético" },
    { "id": "303", "Codigo": "L71", "Descricao": "Neoplasia maligna do aparelho músculo-esquelético", "Categoria": "Músculo-esquelético" },
    { "id": "304", "Codigo": "L72", "Descricao": "Fratura: rádio / cúbito", "Categoria": "Músculo-esquelético" },
    { "id": "305", "Codigo": "L73", "Descricao": "Fratura: tíbia / perónio / fíbula", "Categoria": "Músculo-esquelético" },
    { "id": "306", "Codigo": "L74", "Descricao": "Fratura: osso da mão / pé", "Categoria": "Músculo-esquelético" },
    { "id": "307", "Codigo": "L75", "Descricao": "Fratura: fémur", "Categoria": "Músculo-esquelético" },
    { "id": "308", "Codigo": "L76", "Descricao": "Outras fraturas", "Categoria": "Músculo-esquelético" },
    { "id": "309", "Codigo": "L77", "Descricao": "Entorses e distensões do tornozelo", "Categoria": "Músculo-esquelético" },
    { "id": "310", "Codigo": "L78", "Descricao": "Entorses e distensões do joelho", "Categoria": "Músculo-esquelético" },
    { "id": "311", "Codigo": "L79", "Descricao": "Entorses e distensões das articulações NE", "Categoria": "Músculo-esquelético" },
    { "id": "312", "Codigo": "L80", "Descricao": "Luxação / subluxação", "Categoria": "Músculo-esquelético" },
    { "id": "313", "Codigo": "L81", "Descricao": "Traumatismos do aparelho musculoesquelético NE", "Categoria": "Músculo-esquelético" },
    { "id": "314", "Codigo": "L82", "Descricao": "Malformações congénitas do aparelho musculoesquelético", "Categoria": "Músculo-esquelético" },
    { "id": "315", "Codigo": "L83", "Descricao": "Doenças ou síndromes da coluna cervical", "Categoria": "Músculo-esquelético" },
    { "id": "316", "Codigo": "L84", "Descricao": "Doenças ou síndromes da coluna sem irradiação de dor", "Categoria": "Músculo-esquelético" },
    { "id": "317", "Codigo": "L85", "Descricao": "Deformação adquirida de coluna", "Categoria": "Músculo-esquelético" },
    { "id": "318", "Codigo": "L86", "Descricao": "Síndrome vertebral com irradiação dor", "Categoria": "Músculo-esquelético" },
    { "id": "319", "Codigo": "L87", "Codigo": "Bursite / tendinite / sinovite NE", "Categoria": "Músculo-esquelético" },
    { "id": "320", "Codigo": "L88", "Descricao": "Artrite reumatóide / seropositiva", "Categoria": "Músculo-esquelético" },
    { "id": "321", "Codigo": "L89", "Descricao": "Osteoartrose do quadril", "Categoria": "Músculo-esquelético" },
    { "id": "322", "Codigo": "L90", "Descricao": "Osteoartrose do joelho", "Categoria": "Músculo-esquelético" },
    { "id": "323", "Codigo": "L91", "Descricao": "Outras osteoartroses", "Categoria": "Músculo-esquelético" },
    { "id": "324", "Codigo": "L92", "Descricao": "Síndrome do ombro doloroso", "Categoria": "Músculo-esquelético" },
    { "id": "325", "Codigo": "L93", "Descricao": "Cotovelo de tenista", "Categoria": "Músculo-esquelético" },
    { "id": "326", "Codigo": "L94", "Descricao": "Osteocondrose", "Categoria": "Músculo-esquelético" },
    { "id": "327", "Codigo": "L95", "Descricao": "Osteoporose", "Categoria": "Músculo-esquelético" },
    { "id": "328", "Codigo": "L96", "Descricao": "Lesão interna aguda do joelho", "Categoria": "Músculo-esquelético" },
    { "id": "329", "Codigo": "L97", "Descricao": "Neoplasia benigna / incertas", "Categoria": "Músculo-esquelético" },
    { "id": "330", "Codigo": "L98", "Descricao": "Malformação adquirida de um membro", "Categoria": "Músculo-esquelético" },
    { "id": "331", "Codigo": "L99", "Descricao": "Outra doença do aparelho musculoesquelético", "Categoria": "Músculo-esquelético" },

    // --- NEUROLÓGICO ---
    { "id": "332", "Codigo": "N01", "Descricao": "Cefaleia", "Categoria": "Neurológico" },
    { "id": "333", "Codigo": "N03", "Descricao": "Dores da face", "Categoria": "Neurológico" },
    { "id": "334", "Codigo": "N04", "Descricao": "Síndrome das pernas inquietas", "Categoria": "Neurológico" },
    { "id": "335", "Codigo": "N05", "Descricao": "Formigamento / parestesia nos dedos das mãos / pés", "Categoria": "Neurológico" },
    { "id": "336", "Codigo": "N06", "Descricao": "Outras alterações da sensibilidade", "Categoria": "Neurológico" },
    { "id": "337", "Codigo": "N07", "Descricao": "Convulsões / ataques", "Categoria": "Neurológico" },
    { "id": "338", "Codigo": "N08", "Descricao": "Movimentos involuntários anormais", "Categoria": "Neurológico" },
    { "id": "339", "Codigo": "N16", "Descricao": "Alterações do olfato / gosto", "Categoria": "Neurológico" },
    { "id": "340", "Codigo": "N17", "Descricao": "Vertigens / tonturas", "Categoria": "Neurológico" },
    { "id": "341", "Codigo": "N18", "Descricao": "Paralisia / fraqueza", "Categoria": "Neurológico" },
    { "id": "342", "Codigo": "N19", "Descricao": "Perturbações da fala", "Categoria": "Neurológico" },
    { "id": "343", "Codigo": "N26", "Descricao": "Medo de câncer do sistema neurológico", "Categoria": "Neurológico" },
    { "id": "344", "Codigo": "N27", "Descricao": "Medo de outras doenças neurológicas", "Categoria": "Neurológico" },
    { "id": "345", "Codigo": "N28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Neurológico" },
    { "id": "346", "Codigo": "N29", "Descricao": "Sinais / sintomas do sistema neurológico, outros", "Categoria": "Neurológico" },
    { "id": "65", "Codigo": "N32", "Descricao": "Teste de sensibilidade neurológica", "Categoria": "Neurológico" },
    { "id": "66", "Codigo": "N43", "Descricao": "Outros procedimentos diagnósticos (EEG)", "Categoria": "Neurológico" },
    { "id": "67", "Codigo": "N50", "Descricao": "Prescrição de medicação neurológica", "Categoria": "Neurológico" },
    { "id": "68", "Codigo": "N67", "Descricao": "Encaminhamento para neurologista", "Categoria": "Neurológico" },
    { "id": "347", "Codigo": "N70", "Descricao": "Poliomielite", "Categoria": "Neurológico" },
    { "id": "348", "Codigo": "N71", "Descricao": "Meningite / encefalite", "Categoria": "Neurológico" },
    { "id": "349", "Codigo": "N72", "Descricao": "Tétano", "Categoria": "Neurológico" },
    { "id": "350", "Codigo": "N73", "Descricao": "Outra infecção neurológica", "Categoria": "Neurológico" },
    { "id": "351", "Codigo": "N74", "Descricao": "Neoplasia maligna do sistema neurológico", "Categoria": "Neurológico" },
    { "id": "352", "Codigo": "N75", "Descricao": "Neoplasia benigna do sistema neurológico", "Categoria": "Neurológico" },
    { "id": "353", "Codigo": "N76", "Descricao": "Neoplasia do sistema neurológico de natureza incerta", "Categoria": "Neurológico" },
    { "id": "354", "Codigo": "N79", "Descricao": "Concussão", "Categoria": "Neurológico" },
    { "id": "355", "Codigo": "N80", "Descricao": "Outras lesões cranianas", "Categoria": "Neurológico" },
    { "id": "356", "Codigo": "N81", "Descricao": "Outra lesão do sistema neurológico", "Categoria": "Neurológico" },
    { "id": "357", "Codigo": "N85", "Descricao": "Malformações congénitas", "Categoria": "Neurológico" },
    { "id": "358", "Codigo": "N86", "Descricao": "Esclerose múltipla", "Categoria": "Neurológico" },
    { "id": "359", "Codigo": "N87", "Descricao": "Parkinsonismo", "Categoria": "Neurológico" },
    { "id": "360", "Codigo": "N88", "Descricao": "Epilepsia", "Categoria": "Neurológico" },
    { "id": "361", "Codigo": "N89", "Descricao": "Enxaqueca", "Categoria": "Neurológico" },
    { "id": "362", "Codigo": "N90", "Descricao": "Cefaleia de cluster", "Categoria": "Neurológico" },
    { "id": "363", "Codigo": "N91", "Descricao": "Paralisia facial / paralisia de Bell", "Categoria": "Neurológico" },
    { "id": "364", "Codigo": "N92", "Descricao": "Nevralgia do trigémio", "Categoria": "Neurológico" },
    { "id": "365", "Codigo": "N93", "Descricao": "Síndrome do túnel do carpo / Síndrome de canal cárpico", "Categoria": "Neurológico" },
    { "id": "366", "Codigo": "N94", "Descricao": "Neurite / Neuropatia periférica", "Categoria": "Neurológico" },
    { "id": "367", "Codigo": "N95", "Descricao": "Cefaleia tensional", "Categoria": "Neurológico" },
    { "id": "368", "Codigo": "N99", "Descricao": "Outras doenças do sistema neurológico", "Categoria": "Neurológico" },

    // --- PSICOLÓGICO ---
    { "id": "369", "Codigo": "P01", "Descricao": "Sensação de ansiedade / nervosismo / tensão", "Categoria": "Psicológico" },
    { "id": "370", "Codigo": "P02", "Descricao": "Reação aguda ao estresse", "Categoria": "Psicológico" },
    { "id": "371", "Codigo": "P03", "Descricao": "Tristeza / Sensação de depressão", "Categoria": "Psicológico" },
    { "id": "372", "Codigo": "P04", "Descricao": "Sentir / comportar-se de forma irritável / zangada", "Categoria": "Psicológico" },
    { "id": "373", "Codigo": "P05", "Descricao": "Sensação / comportamento senil", "Categoria": "Psicológico" },
    { "id": "374", "Codigo": "P06", "Descricao": "Perturbação do sono", "Categoria": "Psicológico" },
    { "id": "375", "Codigo": "P07", "Descricao": "Diminuição do desejo sexual", "Categoria": "Psicológico" },
    { "id": "376", "Codigo": "P08", "Descricao": "Diminuição da satisfação sexual", "Categoria": "Psicológico" },
    { "id": "377", "Codigo": "P09", "Descricao": "Preocupação com a preferência sexual", "Categoria": "Psicológico" },
    { "id": "378", "Codigo": "P10", "Descricao": "Gaguejar / balbuciar / tiques", "Categoria": "Psicológico" },
    { "id": "379", "Codigo": "P11", "Descricao": "Problemas de alimentação da criança", "Categoria": "Psicológico" },
    { "id": "380", "Codigo": "P12", "Descricao": "Molhar a cama / enurese", "Categoria": "Psicológico" },
    { "id": "381", "Codigo": "P13", "Descricao": "Encoprese / outros problemas de incontinência fecal", "Categoria": "Psicológico" },
    { "id": "382", "Codigo": "P15", "Descricao": "Abuso crónico de álcool", "Categoria": "Psicológico" },
    { "id": "383", "Codigo": "P16", "Descricao": "Abuso agudo de álcool", "Categoria": "Psicológico" },
    { "id": "384", "Codigo": "P17", "Descricao": "Abuso do tabaco", "Categoria": "Psicológico" },
    { "id": "385", "Codigo": "P18", "Descricao": "Abuso de medicação", "Categoria": "Psicológico" },
    { "id": "386", "Codigo": "P19", "Descricao": "Abuso de drogas", "Categoria": "Psicológico" },
    { "id": "387", "Codigo": "P20", "Descricao": "Alterações da memória", "Categoria": "Psicológico" },
    { "id": "388", "Codigo": "P22", "Descricao": "Sinais / sintomas relacionados ao comportamento da criança", "Categoria": "Psicológico" },
    { "id": "389", "Codigo": "P23", "Descricao": "Sinais / sintomas relacionados ao comportamento do adolescente", "Categoria": "Psicológico" },
    { "id": "390", "Codigo": "P24", "Descricao": "Dificuldades específicas de aprendizagem", "Categoria": "Psicológico" },
    { "id": "391", "Codigo": "P25", "Descricao": "Problemas da fase de vida de adulto", "Categoria": "Psicológico" },
    { "id": "392", "Codigo": "P27", "Descricao": "Medo de perturbações mentais", "Categoria": "Psicológico" },
    { "id": "393", "Codigo": "P28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Psicológico" },
    { "id": "394", "Codigo": "P29", "Descricao": "Sinais / sintomas psicológicos, outros", "Categoria": "Psicológico" },
    { "id": "69", "Codigo": "P45", "Descricao": "Educação em saúde / aconselhamento psicológico", "Categoria": "Psicológico" },
    { "id": "70", "Codigo": "P50", "Descricao": "Prescrição de medicação psicotrópica", "Categoria": "Psicológico" },
    { "id": "71", "Codigo": "P58", "Descricao": "Aconselhamento / escuta terapêutica (Psicoterapia)", "Categoria": "Psicológico" },
    { "id": "72", "Codigo": "P67", "Descricao": "Encaminhamento para psiquiatra / psicólogo", "Categoria": "Psicológico" },
    { "id": "395", "Codigo": "P70", "Descricao": "Demência", "Categoria": "Psicológico" },
    { "id": "396", "Codigo": "P71", "Descricao": "Outras psicoses orgânicas NE", "Categoria": "Psicológico" },
    { "id": "397", "Codigo": "P72", "Descricao": "Esquizofrenia", "Categoria": "Psicológico" },
    { "id": "398", "Codigo": "P73", "Descricao": "Psicose afetiva", "Categoria": "Psicológico" },
    { "id": "399", "Codigo": "P74", "Descricao": "Distúrbio ansioso / estado de ansiedade", "Categoria": "Psicológico" },
    { "id": "400", "Codigo": "P75", "Descricao": "Somatização", "Categoria": "Psicológico" },
    { "id": "401", "Codigo": "P76", "Descricao": "Perturbações depressivas", "Categoria": "Psicológico" },
    { "id": "402", "Codigo": "P77", "Descricao": "Suicídio / tentativa de suicídio", "Categoria": "Psicológico" },
    { "id": "403", "Codigo": "P78", "Descricao": "Neurastenia", "Categoria": "Psicológico" },
    { "id": "404", "Codigo": "P79", "Descricao": "Fobia / perturbação compulsiva", "Categoria": "Psicológico" },
    { "id": "405", "Codigo": "P80", "Descricao": "Perturbações de personalidade", "Categoria": "Psicológico" },
    { "id": "406", "Codigo": "P81", "Descricao": "Perturbação hipercinética", "Categoria": "Psicológico" },
    { "id": "407", "Codigo": "P82", "Descricao": "Estresse pós traumático", "Categoria": "Psicológico" },
    { "id": "408", "Codigo": "P85", "Descricao": "Retardo / Atraso mental", "Categoria": "Psicológico" },
    { "id": "409", "Codigo": "P86", "Descricao": "Anorexia nervosa, bulimia", "Categoria": "Psicológico" },
    { "id": "410", "Codigo": "P98", "Descricao": "Outras psicoses NE", "Categoria": "Psicológico" },
    { "id": "411", "Codigo": "P99", "Descricao": "Outras perturbações psicológicas", "Categoria": "Psicológico" },

    // --- RESPIRATÓRIO ---
    { "id": "412", "Codigo": "R01", "Descricao": "Dor atribuída ao aparelho respiratório", "Categoria": "Respiratório" },
    { "id": "413", "Codigo": "R02", "Descricao": "Dificuldade respiratória, dispneia", "Categoria": "Respiratório" },
    { "id": "414", "Codigo": "R03", "Descricao": "Respiração ruidosa", "Categoria": "Respiratório" },
    { "id": "415", "Codigo": "R04", "Descricao": "Outros problemas respiratórios", "Categoria": "Respiratório" },
    { "id": "416", "Codigo": "R05", "Descricao": "Tosse", "Categoria": "Respiratório" },
    { "id": "417", "Codigo": "R06", "Descricao": "Hemorragia nasal / epistaxe", "Categoria": "Respiratório" },
    { "id": "418", "Codigo": "R07", "Descricao": "Espirro / congestão nasal", "Categoria": "Respiratório" },
    { "id": "419", "Codigo": "R08", "Descricao": "Outros sinais / sintomas nasais", "Categoria": "Respiratório" },
    { "id": "420", "Codigo": "R09", "Descricao": "Sinais / sintomas dos seios paranasais", "Categoria": "Respiratório" },
    { "id": "421", "Codigo": "R21", "Descricao": "Sinais / sintomas da garganta", "Categoria": "Respiratório" },
    { "id": "422", "Codigo": "R23", "Descricao": "Sinais / sintomas da voz", "Categoria": "Respiratório" },
    { "id": "423", "Codigo": "R24", "Descricao": "Hemoptise", "Categoria": "Respiratório" },
    { "id": "424", "Codigo": "R25", "Descricao": "Expectoração / mucosidade anormal", "Categoria": "Respiratório" },
    { "id": "425", "Codigo": "R26", "Descricao": "Medo de câncer do aparelho respiratório", "Categoria": "Respiratório" },
    { "id": "426", "Codigo": "R27", "Descricao": "Medo de outras doenças respiratórias", "Categoria": "Respiratório" },
    { "id": "427", "Codigo": "R28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Respiratório" },
    { "id": "428", "Codigo": "R29", "Descricao": "Sinais / sintomas do aparelho respiratório, outros", "Categoria": "Respiratório" },
    { "id": "73", "Codigo": "R33", "Descricao": "Exame microbiológico respiratório (Bactoscopia)", "Categoria": "Respiratório" },
    { "id": "74", "Codigo": "R39", "Descricao": "Teste de função física respiratória (Espirometria)", "Categoria": "Respiratório" },
    { "id": "75", "Codigo": "R41", "Descricao": "Radiologia diagnóstica (Raio-X de tórax)", "Categoria": "Respiratório" },
    { "id": "76", "Codigo": "R50", "Descricao": "Prescrição de medicação respiratória (Inaladores)", "Categoria": "Respiratório" },
    { "id": "429", "Codigo": "R71", "Descricao": "Tosse convulsa / pertussis", "Categoria": "Respiratório" },
    { "id": "430", "Codigo": "R72", "Descricao": "Infecção estreptocócica da orofaringe", "Categoria": "Respiratório" },
    { "id": "431", "Codigo": "R73", "Descricao": "Abcesso / furúnculo no nariz", "Categoria": "Respiratório" },
    { "id": "432", "Codigo": "R74", "Descricao": "Infecção aguda do aparelho respiratório superior (IVAS)", "Categoria": "Respiratório" },
    { "id": "433", "Codigo": "R75", "Descricao": "Sinusite crónica / aguda", "Categoria": "Respiratório" },
    { "id": "434", "Codigo": "R76", "Descricao": "Amigdalite aguda", "Categoria": "Respiratório" },
    { "id": "435", "Codigo": "R77", "Descricao": "Laringite / traqueite aguda", "Categoria": "Respiratório" },
    { "id": "436", "Codigo": "R78", "Descricao": "Bronquite / bronquiolite aguda", "Categoria": "Respiratório" },
    { "id": "437", "Codigo": "R79", "Descricao": "Bronquite crónica", "Categoria": "Respiratório" },
    { "id": "438", "Codigo": "R80", "Descricao": "Gripe", "Categoria": "Respiratório" },
    { "id": "439", "Codigo": "R81", "Descricao": "Pneumonia", "Categoria": "Respiratório" },
    { "id": "440", "Codigo": "R82", "Descricao": "Pleurite / derrame pleural", "Categoria": "Respiratório" },
    { "id": "441", "Codigo": "R83", "Descricao": "Outra infecção respiratória", "Categoria": "Respiratório" },
    { "id": "442", "Codigo": "R84", "Descricao": "Neoplasia maligna dos brônquios / pulmão", "Categoria": "Respiratório" },
    { "id": "443", "Codigo": "R85", "Descricao": "Outra neoplasia respiratória maligna", "Categoria": "Respiratório" },
    { "id": "444", "Codigo": "R86", "Descricao": "Neoplasia benigna respiratória", "Categoria": "Respiratório" },
    { "id": "445", "Codigo": "R87", "Descricao": "Corpo estranho nariz / laringe / brônquios", "Categoria": "Respiratório" },
    { "id": "446", "Codigo": "R88", "Descricao": "Outra lesão respiratória", "Categoria": "Respiratório" },
    { "id": "447", "Codigo": "R89", "Descricao": "Malformação congénita do aparelho respiratório", "Categoria": "Respiratório" },
    { "id": "448", "Codigo": "R90", "Descricao": "Hipertrofia das amígdalas / adenoides", "Categoria": "Respiratório" },
    { "id": "449", "Codigo": "R92", "Descricao": "Neoplasia respiratória NE", "Categoria": "Respiratório" },
    { "id": "450", "Codigo": "R95", "Descricao": "Doença pulmonar obstrutiva crónica (DPOC)", "Categoria": "Respiratório" },
    { "id": "451", "Codigo": "R96", "Descricao": "Asma", "Categoria": "Respiratório" },
    { "id": "452", "Codigo": "R97", "Descricao": "Rinite alérgica", "Categoria": "Respiratório" },
    { "id": "453", "Codigo": "R98", "Descricao": "Síndrome de hiperventilação", "Categoria": "Respiratório" },
    { "id": "454", "Codigo": "R99", "Descricao": "Outras doenças respiratórias", "Categoria": "Respiratório" },

    // --- PELE ---
    { "id": "455", "Codigo": "S01", "Descricao": "Dor / sensibilidade dolorosa da pele", "Categoria": "Pele" },
    { "id": "456", "Codigo": "S02", "Descricao": "Prurido", "Categoria": "Pele" },
    { "id": "457", "Codigo": "S03", "Descricao": "Verrugas", "Categoria": "Pele" },
    { "id": "458", "Codigo": "S04", "Descricao": "Tumor / inchaço localizado", "Categoria": "Pele" },
    { "id": "459", "Codigo": "S05", "Descricao": "Tumores / inchaços generalizados", "Categoria": "Pele" },
    { "id": "460", "Codigo": "S06", "Descricao": "Erupção cutânea localizada", "Categoria": "Pele" },
    { "id": "461", "Codigo": "S07", "Descricao": "Erupção cutânea generalizada", "Categoria": "Pele" },
    { "id": "462", "Codigo": "S08", "Descricao": "Alterações da cor da pele", "Categoria": "Pele" },
    { "id": "463", "Codigo": "S09", "Descricao": "Infecção dos dedos das mãos / pés", "Categoria": "Pele" },
    { "id": "464", "Codigo": "S10", "Descricao": "Furúnculo / carbúnculo", "Categoria": "Pele" },
    { "id": "465", "Codigo": "S11", "Descricao": "Infecção pós-traumática da pele", "Categoria": "Pele" },
    { "id": "466", "Codigo": "S12", "Descricao": "Picada ou mordedura de inseto", "Categoria": "Pele" },
    { "id": "467", "Codigo": "S13", "Descricao": "Mordedura animal / humana", "Categoria": "Pele" },
    { "id": "468", "Codigo": "S14", "Descricao": "Queimadura / escaldão", "Categoria": "Pele" },
    { "id": "469", "Codigo": "S15", "Descricao": "Corpo estranho na pele", "Categoria": "Pele" },
    { "id": "470", "Codigo": "S16", "Descricao": "Traumatismo / contusão", "Categoria": "Pele" },
    { "id": "471", "Codigo": "S17", "Descricao": "Abrasão / arranhão / bolhas", "Categoria": "Pele" },
    { "id": "472", "Codigo": "S18", "Descricao": "Laceração / corte", "Categoria": "Pele" },
    { "id": "473", "Codigo": "S19", "Descricao": "Outra lesão cutânea", "Categoria": "Pele" },
    { "id": "474", "Codigo": "S20", "Descricao": "Calos / calosidades", "Categoria": "Pele" },
    { "id": "475", "Codigo": "S21", "Descricao": "Sinais / sintomas da textura da pele", "Categoria": "Pele" },
    { "id": "476", "Codigo": "S22", "Descricao": "Sinais / sintomas das unhas", "Categoria": "Pele" },
    { "id": "477", "Codigo": "S23", "Descricao": "Queda de cabelo / calvície", "Categoria": "Pele" },
    { "id": "478", "Codigo": "S24", "Descricao": "Sinais / sintomas do cabelo / couro cabeludo", "Categoria": "Pele" },
    { "id": "479", "Codigo": "S26", "Descricao": "Medo de câncer de pele", "Categoria": "Pele" },
    { "id": "480", "Codigo": "S27", "Descricao": "Medo de outra doença da pele", "Categoria": "Pele" },
    { "id": "481", "Codigo": "S28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Pele" },
    { "id": "482", "Codigo": "S29", "Descricao": "Sinais / sintomas da pele, outros", "Categoria": "Pele" },
    { "id": "77", "Codigo": "S37", "Descricao": "Biópsia / histologia de lesão cutânea", "Categoria": "Pele" },
    { "id": "78", "Codigo": "S51", "Descricao": "Incisão e drenagem de abscesso cutâneo", "Categoria": "Pele" },
    { "id": "79", "Codigo": "S52", "Descricao": "Excisão / cauterização / debridamento de pele", "Categoria": "Pele" },
    { "id": "80", "Codigo": "S54", "Descricao": "Sutura de laceração cutânea", "Categoria": "Pele" },
    { "id": "483", "Codigo": "S70", "Descricao": "Herpes zoster", "Categoria": "Pele" },
    { "id": "484", "Codigo": "S71", "Descricao": "Herpes simples", "Categoria": "Pele" },
    { "id": "485", "Codigo": "S72", "Descricao": "Escabiose / outras acariases", "Categoria": "Pele" },
    { "id": "486", "Codigo": "S73", "Descricao": "Pediculose / outras infecções da pele", "Categoria": "Pele" },
    { "id": "487", "Codigo": "S74", "Descricao": "Dermatofitose", "Categoria": "Pele" },
    { "id": "488", "Codigo": "S75", "Descricao": "Monilíase oral / candidíase na pele", "Categoria": "Pele" },
    { "id": "489", "Codigo": "S76", "Descricao": "Outras infecções da pele", "Categoria": "Pele" },
    { "id": "490", "Codigo": "S77", "Descricao": "Neoplasias malignas da pele", "Categoria": "Pele" },
    { "id": "491", "Codigo": "S78", "Descricao": "Lipoma", "Categoria": "Pele" },
    { "id": "492", "Codigo": "S79", "Descricao": "Neoplasia cutânea benigna / incerta", "Categoria": "Pele" },
    { "id": "493", "Codigo": "S80", "Descricao": "Ceratose / Queratose solar / queimadura solar", "Categoria": "Pele" },
    { "id": "494", "Codigo": "S81", "Descricao": "Hemangioma / linfangioma", "Categoria": "Pele" },
    { "id": "495", "Codigo": "S82", "Descricao": "Nevos / sinais da pele", "Categoria": "Pele" },
    { "id": "496", "Codigo": "S83", "Descricao": "Lesões da pele congénitas, outras", "Categoria": "Pele" },
    { "id": "497", "Codigo": "S84", "Descricao": "Impetigo", "Categoria": "Pele" },
    { "id": "498", "Codigo": "S85", "Descricao": "Cisto pilonidal / fístula", "Categoria": "Pele" },
    { "id": "499", "Codigo": "S86", "Descricao": "Dermatite seborreica", "Categoria": "Pele" },
    { "id": "500", "Codigo": "S87", "Descricao": "Dermatite / eczema atópico", "Categoria": "Pele" },
    { "id": "501", "Codigo": "S88", "Descricao": "Dermatite de contato alérgica", "Categoria": "Pele" },
    { "id": "502", "Codigo": "S89", "Descricao": "Dermatite das fraldas", "Categoria": "Pele" },
    { "id": "503", "Codigo": "S90", "Descricao": "Pitiríase rósea", "Categoria": "Pele" },
    { "id": "504", "Codigo": "S91", "Descricao": "Psoríase", "Categoria": "Pele" },
    { "id": "505", "Codigo": "S92", "Descricao": "Doença das glândulas sudoríparas", "Categoria": "Pele" },
    { "id": "506", "Codigo": "S93", "Descricao": "Cisto sebáceo", "Categoria": "Pele" },
    { "id": "507", "Codigo": "S94", "Descricao": "Unha encravada", "Categoria": "Pele" },
    { "id": "508", "Codigo": "S95", "Descricao": "Molusco contagioso", "Categoria": "Pele" },
    { "id": "509", "Codigo": "S96", "Descricao": "Acne", "Categoria": "Pele" },
    { "id": "510", "Codigo": "S97", "Descricao": "Úlcera crónica da pele", "Categoria": "Pele" },
    { "id": "511", "Codigo": "S98", "Descricao": "Urticária", "Categoria": "Pele" },
    { "id": "512", "Codigo": "S99", "Descricao": "Outras doenças da pele", "Categoria": "Pele" },

    // --- ENDÓCRINO / METABÓLICO / NUTRICIONAL ---
    { "id": "513", "Codigo": "T01", "Descricao": "Sede excessiva", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "514", "Codigo": "T02", "Descricao": "Apetite excessivo", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "515", "Codigo": "T03", "Descricao": "Perda de apetite", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "516", "Codigo": "T04", "Descricao": "Problemas alimentares de lactente / criança", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "517", "Codigo": "T05", "Descricao": "Problemas alimentares do adulto", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "518", "Codigo": "T07", "Descricao": "Aumento de peso", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "519", "Codigo": "T08", "Descricao": "Perda de peso", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "520", "Codigo": "T10", "Descricao": "Atraso do crescimento", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "521", "Codigo": "T11", "Descricao": "Desidratação", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "522", "Codigo": "T26", "Descricao": "Medo de câncer do sistema endócrino", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "523", "Codigo": "T27", "Descricao": "Medo de outra doença endócrina / metabólica", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "524", "Codigo": "T28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "525", "Codigo": "T29", "Descricao": "Sinais / sintomas endócrinológicos / metabólicos / nutricionais, outros", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "81", "Codigo": "T34", "Descricao": "Análise de sangue (Glicemia, perfil lipídico, tireoide)", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "82", "Codigo": "T45", "Descricao": "Aconselhamento nutricional e dieta", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "83", "Codigo": "T50", "Descricao": "Prescrição de insulina / antidiabéticos / hormônios", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "84", "Codigo": "T66", "Descricao": "Encaminhamento para nutricionista", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "526", "Codigo": "T70", "Descricao": "Infecção endócrina", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "527", "Codigo": "T71", "Descricao": "Neoplasia maligna da tiroide", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "528", "Codigo": "T72", "Descricao": "Neoplasia benigna da tiroide", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "529", "Codigo": "T73", "Descricao": "Outra neoplasia endócrina NE", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "530", "Codigo": "T78", "Descricao": "Cisto do canal tiroglosso", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "531", "Codigo": "T80", "Descricao": "Malformação congénita endócrina / metabólica", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "532", "Codigo": "T81", "Descricao": "Bócio", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "533", "Codigo": "T82", "Descricao": "Obesidade", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "534", "Codigo": "T83", "Descricao": "Excesso de peso", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "535", "Codigo": "T85", "Descricao": "Hipertiroidismo / tireotoxicose", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "536", "Codigo": "T86", "Descricao": "Hipotiroidismo / mixedema", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "537", "Codigo": "T87", "Descricao": "Hipoglicemia", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "538", "Codigo": "T89", "Descricao": "Diabetes insulino-dependente", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "539", "Codigo": "T90", "Descricao": "Diabetes não insulino-dependente", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "540", "Codigo": "T91", "Descricao": "Deficiência vitamínica / nutricional", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "541", "Codigo": "T92", "Descricao": "Gota", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "542", "Codigo": "T93", "Descricao": "Alteração no metabolismo dos lípidos", "Categoria": "Endócrino / Metabólico / Nutricional" },
    { "id": "543", "Codigo": "T99", "Descricao": "Outras doenças endocrinológica / metabólica / nutricionais", "Categoria": "Endócrino / Metabólico / Nutricional" },

    // --- URINÁRIO ---
    { "id": "544", "Codigo": "U01", "Descricao": "Disúria / micção dolorosa", "Categoria": "Urinário" },
    { "id": "545", "Codigo": "U02", "Descricao": "Micção frequente / urgência urinária / polaciúria", "Categoria": "Urinário" },
    { "id": "546", "Codigo": "U04", "Descricao": "Incontinência urinária", "Categoria": "Urinário" },
    { "id": "547", "Codigo": "U05", "Descricao": "Outros problemas com a micção", "Categoria": "Urinário" },
    { "id": "548", "Codigo": "U06", "Descricao": "Hematúria", "Categoria": "Urinário" },
    { "id": "549", "Codigo": "U07", "Descricao": "Outros sinais / sintomas urinários", "Categoria": "Urinário" },
    { "id": "550", "Codigo": "U08", "Descricao": "Retenção urinária", "Categoria": "Urinário" },
    { "id": "551", "Codigo": "U13", "Descricao": "Sinais / sintomas da bexiga, outros", "Categoria": "Urinário" },
    { "id": "552", "Codigo": "U14", "Descricao": "Sinais / sintomas dos rins", "Categoria": "Urinário" },
    { "id": "553", "Codigo": "U26", "Descricao": "Medo de câncer no aparelho urinário", "Categoria": "Urinário" },
    { "id": "554", "Codigo": "U27", "Descricao": "Medo de outra doença urinária", "Categoria": "Urinário" },
    { "id": "555", "Codigo": "U28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Urinário" },
    { "id": "556", "Codigo": "U29", "Descricao": "Sinais / sintomas aparelho urinário, outros", "Categoria": "Urinário" },
    { "id": "85", "Codigo": "U35", "Descricao": "Análise de urina (EAS, urinocultura)", "Categoria": "Urinário" },
    { "id": "86", "Codigo": "U41", "Descricao": "Radiologia / ultrassonografia diagnóstica urinária", "Categoria": "Urinário" },
    { "id": "87", "Codigo": "U53", "Descricao": "Cateterização vesical / Sondagem urinária", "Categoria": "Urinário" },
    { "id": "88", "Codigo": "U67", "Descricao": "Encaminhamento para urologista / nefrologista", "Categoria": "Urinário" },
    { "id": "557", "Codigo": "U70", "Descricao": "Pielonefrite", "Categoria": "Urinário" },
    { "id": "558", "Codigo": "U71", "Descricao": "Cistite / outra infecção urinária", "Categoria": "Urinário" },
    { "id": "559", "Codigo": "U72", "Descricao": "Uretrite", "Categoria": "Urinário" },
    { "id": "560", "Codigo": "U75", "Descricao": "Neoplasia maligna do rim", "Categoria": "Urinário" },
    { "id": "561", "Codigo": "U76", "Descricao": "Neoplasia benigna do rim", "Categoria": "Urinário" },
    { "id": "562", "Codigo": "U77", "Descricao": "Neoplasia maligna do aparelho urinário, outra", "Categoria": "Urinário" },
    { "id": "563", "Codigo": "U78", "Descricao": "Neoplasia benigna do aparelho urinário", "Categoria": "Urinário" },
    { "id": "564", "Codigo": "U79", "Descricao": "Neoplasia do aparelho urinário NE", "Categoria": "Urinário" },
    { "id": "565", "Codigo": "U80", "Descricao": "Lesões traumáticas do aparelho urinário", "Categoria": "Urinário" },
    { "id": "566", "Codigo": "U85", "Descricao": "Malformação congénita do aparelho urinário", "Categoria": "Urinário" },
    { "id": "567", "Codigo": "U88", "Descricao": "Glomerulonefrite / síndrome nefrótica", "Categoria": "Urinário" },
    { "id": "568", "Codigo": "U90", "Descricao": "Albuminúria / proteinúria ortostática", "Categoria": "Urinário" },
    { "id": "569", "Codigo": "U95", "Descricao": "Cálculo urinário", "Categoria": "Urinário" },
    { "id": "570", "Codigo": "U98", "Descricao": "Análise de urina anormal NE", "Categoria": "Urinário" },
    { "id": "571", "Codigo": "U99", "Descricao": "Outras doenças urinárias", "Categoria": "Urinário" },

    // --- GRAVIDEZ, PARTO E PLANEJAMENTO FAMILIAR ---
    { "id": "572", "Codigo": "W01", "Descricao": "Questão sobre gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "573", "Codigo": "W02", "Descricao": "Medo de estar grávida", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "574", "Codigo": "W03", "Descricao": "Hemorragia antes do parto", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "575", "Codigo": "W05", "Descricao": "Vómitos / náuseas durante a gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "576", "Codigo": "W10", "Descricao": "Contracepção pós-coital", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "577", "Codigo": "W11", "Descricao": "Contracepção oral", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "578", "Codigo": "W12", "Descricao": "Contracepção intra-uterina / Dispositivo Intrauterino / DIU", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "579", "Codigo": "W13", "Descricao": "Esterilização", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "580", "Codigo": "W14", "Descricao": "Contracepção / outros", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "581", "Codigo": "W15", "Descricao": "Infertilidade / subfertividade", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "582", "Codigo": "W17", "Descricao": "Hemorragia pós-parto", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "583", "Codigo": "W18", "Descricao": "Sinais / sintomas pós-parto", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "584", "Codigo": "W19", "Descricao": "Sinais / sintomas da mama / lactação", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "585", "Codigo": "W21", "Descricao": "Preocupação com a imagem corporal na gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "586", "Codigo": "W27", "Descricao": "Medo de complicações na gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "587", "Codigo": "W28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "588", "Codigo": "W29", "Descricao": "Sinais / sintomas da gravidez, outros", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "89", "Codigo": "W30", "Descricao": "Exame / avaliação completa de pré-natal", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "90", "Codigo": "W35", "Descricao": "Teste de gravidez na urina (Beta-HCG)", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "91", "Codigo": "W41", "Descricao": "Ultrassonografia obstétrica", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "92", "Codigo": "W45", "Descricao": "Aconselhamento em planejamento familiar e amamentação", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "589", "Codigo": "W70", "Descricao": "Sepsis / infecção puerperal", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "590", "Codigo": "W71", "Descricao": "Infecções que complicam a gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "591", "Codigo": "W72", "Descricao": "Neoplasia maligna relacionada com gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "592", "Codigo": "W73", "Descricao": "Neoplasia benigna / incerta relacionada com a gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "593", "Codigo": "W75", "Descricao": "Lesões traumáticas que complicam a gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "594", "Codigo": "W76", "Descricao": "Malformação congénita que complica a gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "595", "Codigo": "W78", "Descricao": "Gravidez", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "596", "Codigo": "W79", "Descricao": "Gravidez não desejada", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "597", "Codigo": "W80", "Descricao": "Gravidez ectópica", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "598", "Codigo": "W81", "Descricao": "Toxemia gravídica / DHEG", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "599", "Codigo": "W82", "Descricao": "Aborto espontâneo", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "600", "Codigo": "W83", "Descricao": "Aborto provocado", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "601", "Codigo": "W84", "Descricao": "Gravidez de alto risco", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "602", "Codigo": "W85", "Descricao": "Diabetes gestacional", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "603", "Codigo": "W90", "Descricao": "Parto sem complicações de nascido vivo", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "604", "Codigo": "W91", "Descricao": "Parto sem complicações de natimorto", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "605", "Codigo": "W92", "Descricao": "Parto com complicações de nascido vivo", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "606", "Codigo": "W93", "Descricao": "Parto com complicações de natimorto", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "607", "Codigo": "W94", "Descricao": "Mastite puerperal", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "608", "Codigo": "W95", "Descricao": "Outros problemas da mama durante gravidez / puerpério", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "609", "Codigo": "W96", "Descricao": "Outras complicações do puerpério", "Categoria": "Gravidez, parto e planejamento familiar" },
    { "id": "610", "Codigo": "W99", "Descricao": "Outros problemas da gravidez / parto", "Categoria": "Gravidez, parto e planejamento familiar" },

    // --- GENITAL FEMININO ---
    { "id": "611", "Codigo": "X01", "Descricao": "Dor genital", "Categoria": "Genital feminino" },
    { "id": "612", "Codigo": "X02", "Descricao": "Dores menstruais", "Categoria": "Genital feminino" },
    { "id": "613", "Codigo": "X03", "Descricao": "Dores intermenstruais", "Categoria": "Genital feminino" },
    { "id": "614", "Codigo": "X04", "Descricao": "Relação sexual dolorosa na mulher", "Categoria": "Genital feminino" },
    { "id": "615", "Codigo": "X05", "Descricao": "Menstruação escassa / ausente", "Categoria": "Genital feminino" },
    { "id": "616", "Codigo": "X06", "Descricao": "Menstruação excessiva", "Categoria": "Genital feminino" },
    { "id": "617", "Codigo": "X07", "Descricao": "Menstruação irregular / frequente", "Categoria": "Genital feminino" },
    { "id": "618", "Codigo": "X08", "Descricao": "Hemorragia intermenstrual", "Categoria": "Genital feminino" },
    { "id": "619", "Codigo": "X09", "Descricao": "Sinais / sintomas pré-menstruais", "Categoria": "Genital feminino" },
    { "id": "620", "Codigo": "X10", "Descricao": "Desejo de alterar a data menstruação", "Categoria": "Genital feminino" },
    { "id": "621", "Codigo": "X11", "Descricao": "Sinais / sintomas da menopausa / climatério", "Categoria": "Genital feminino" },
    { "id": "622", "Codigo": "X12", "Descricao": "Hemorragia pós-menopausa", "Categoria": "Genital feminino" },
    { "id": "623", "Codigo": "X13", "Descricao": "Hemorragia pós-coital", "Categoria": "Genital feminino" },
    { "id": "624", "Codigo": "X14", "Descricao": "Secreção vaginal", "Categoria": "Genital feminino" },
    { "id": "625", "Codigo": "X15", "Descricao": "Sinais / sintomas da vagina", "Categoria": "Genital feminino" },
    { "id": "626", "Codigo": "X16", "Descricao": "Sinais / sintomas da vulva", "Categoria": "Genital feminino" },
    { "id": "627", "Codigo": "X17", "Descricao": "Sinais / sintomas da pélvis feminina", "Categoria": "Genital feminino" },
    { "id": "628", "Codigo": "X18", "Descricao": "Dor na mama feminina", "Categoria": "Genital feminino" },
    { "id": "629", "Codigo": "X19", "Descricao": "Tumor ou nódulo na mama feminina", "Categoria": "Genital feminino" },
    { "id": "630", "Codigo": "X20", "Descricao": "Sinais / sintomas do mamilo da mulher", "Categoria": "Genital feminino" },
    { "id": "631", "Codigo": "X21", "Descricao": "Sinais / sintomas da mama feminina, outros", "Categoria": "Genital feminino" },
    { "id": "632", "Codigo": "X22", "Descricao": "Preocupação com a aparência da mama feminina", "Categoria": "Genital feminino" },
    { "id": "633", "Codigo": "X23", "Descricao": "Medo de doença de transmissão sexual", "Categoria": "Genital feminino" },
    { "id": "634", "Codigo": "X24", "Descricao": "Medo de disfunção sexual", "Categoria": "Genital feminino" },
    { "id": "635", "Codigo": "X25", "Descricao": "Medo de câncer genital", "Categoria": "Genital feminino" },
    { "id": "636", "Codigo": "X26", "Descricao": "Medo de câncer na mama", "Categoria": "Genital feminino" },
    { "id": "637", "Codigo": "X27", "Descricao": "Medo de outra doença genital / mama", "Categoria": "Genital feminino" },
    { "id": "638", "Codigo": "X28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Genital feminino" },
    { "id": "639", "Codigo": "X29", "Descricao": "Sinais / sintomas do aparelho genital feminino, outra", "Categoria": "Genital feminino" },
    { "id": "93", "Codigo": "X37", "Descricao": "Citologia esfoliativa / histologia (Papanicolau)", "Categoria": "Genital feminino" },
    { "id": "94", "Codigo": "X41", "Descricao": "Mamografia / Ultrassonografia pélvica", "Categoria": "Genital feminino" },
    { "id": "95", "Codigo": "X50", "Descricao": "Prescrição de anticoncepcionais / TRH", "Categoria": "Genital feminino" },
    { "id": "96", "Codigo": "X67", "Descricao": "Encaminhamento para ginecologista", "Categoria": "Genital feminino" },
    { "id": "640", "Codigo": "X70", "Descricao": "Sífilis feminina", "Categoria": "Genital feminino" },
    { "id": "641", "Codigo": "X71", "Descricao": "Gonorreia feminina", "Categoria": "Genital feminino" },
    { "id": "642", "Codigo": "X72", "Descricao": "Candidíase genital feminina", "Categoria": "Genital feminino" },
    { "id": "643", "Codigo": "X73", "Descricao": "Tricomoníase genital feminina", "Categoria": "Genital feminino" },
    { "id": "644", "Codigo": "X74", "Descricao": "Doença inflamatória pélvica", "Categoria": "Genital feminino" },
    { "id": "645", "Codigo": "X75", "Descricao": "Neoplasia maligna do colo", "Categoria": "Genital feminino" },
    { "id": "646", "Codigo": "X76", "Descricao": "Neoplasia maligna da mama feminina", "Categoria": "Genital feminino" },
    { "id": "647", "Codigo": "X77", "Descricao": "Neoplasia maligna genital feminina, outra", "Categoria": "Genital feminino" },
    { "id": "648", "Codigo": "X78", "Descricao": "Fibromioma uterino", "Categoria": "Genital feminino" },
    { "id": "649", "Codigo": "X79", "Descricao": "Neoplasia benigna da mama feminina / fibroadenoma", "Categoria": "Genital feminino" },
    { "id": "650", "Codigo": "X80", "Descricao": "Neoplasia benigna genital", "Categoria": "Genital feminino" },
    { "id": "651", "Codigo": "X81", "Descricao": "Neoplasia genital feminina, outra / NE", "Categoria": "Genital feminino" },
    { "id": "652", "Codigo": "X82", "Descricao": "Lesão traumática genital feminina", "Categoria": "Genital feminino" },
    { "id": "653", "Codigo": "X83", "Descricao": "Malformações congénitas genitais", "Categoria": "Genital feminino" },
    { "id": "654", "Codigo": "X84", "Descricao": "Vaginite / vulvite NE", "Categoria": "Genital feminino" },
    { "id": "655", "Codigo": "X85", "Descricao": "Doença do colo NE", "Categoria": "Genital feminino" },
    { "id": "656", "Codigo": "X86", "Descricao": "Esfregaço de Papanicolaou / colpocitologia oncótica anormal", "Categoria": "Genital feminino" },
    { "id": "657", "Codigo": "X87", "Descricao": "Prolapso utero-vaginal", "Categoria": "Genital feminino" },
    { "id": "658", "Codigo": "X88", "Descricao": "Doença fibrocística da mama", "Categoria": "Genital feminino" },
    { "id": "659", "Codigo": "X89", "Descricao": "Síndrome da tensão pré-menstrual", "Categoria": "Genital feminino" },
    { "id": "660", "Codigo": "X90", "Descricao": "Herpes genital feminino", "Categoria": "Genital feminino" },
    { "id": "661", "Codigo": "X91", "Descricao": "Condiloma acuminado feminino", "Categoria": "Genital feminino" },
    { "id": "662", "Codigo": "X92", "Descricao": "Infecção por clamídia", "Categoria": "Genital feminino" },
    { "id": "663", "Codigo": "X99", "Descricao": "Doença genital feminina, outra", "Categoria": "Genital feminino" },

    // --- GENITAL MASCULINO ---
    { "id": "664", "Codigo": "Y01", "Descricao": "Dor no pênis", "Categoria": "Genital masculino" },
    { "id": "665", "Codigo": "Y02", "Descricao": "Dor no escroto / testículos", "Categoria": "Genital masculino" },
    { "id": "666", "Codigo": "Y03", "Descricao": "Secreção uretral", "Categoria": "Genital masculino" },
    { "id": "667", "Codigo": "Y04", "Descricao": "Sinais / sintomas do pênis, outros", "Categoria": "Genital masculino" },
    { "id": "668", "Codigo": "Y05", "Descricao": "Sinais / sintomas do escroto / testículos, outros", "Categoria": "Genital masculino" },
    { "id": "669", "Codigo": "Y06", "Descricao": "Sinais / sintomas da prós-tata", "Categoria": "Genital masculino" },
    { "id": "670", "Codigo": "Y07", "Descricao": "Impotência NE", "Categoria": "Genital masculino" },
    { "id": "671", "Codigo": "Y08", "Descricao": "Sinais / sintomas da função sexual masculina, outros", "Categoria": "Genital masculino" },
    { "id": "672", "Codigo": "Y10", "Descricao": "Infertilidade / subfertilidade masculina", "Categoria": "Genital masculino" },
    { "id": "673", "Codigo": "Y13", "Descricao": "Esterilização masculina", "Categoria": "Genital masculino" },
    { "id": "674", "Codigo": "Y14", "Descricao": "Planejamento familiar, outros", "Categoria": "Genital masculino" },
    { "id": "675", "Codigo": "Y16", "Descricao": "Sinais / sintomas da mama masculina", "Categoria": "Genital masculino" },
    { "id": "676", "Codigo": "Y24", "Descricao": "Medo de disfunção sexual masculina", "Categoria": "Genital masculino" },
    { "id": "677", "Codigo": "Y25", "Descricao": "Medo de doença sexualmente transmissível", "Categoria": "Genital masculino" },
    { "id": "678", "Codigo": "Y26", "Descricao": "Medo de câncer genital masculino", "Categoria": "Genital masculino" },
    { "id": "679", "Codigo": "Y27", "Descricao": "Medo de doença genital masculina, outra", "Categoria": "Genital masculino" },
    { "id": "680", "Codigo": "Y28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Genital masculino" },
    { "id": "681", "Codigo": "Y29", "Descricao": "Sinais / sintomas, outros", "Categoria": "Genital masculino" },
    { "id": "97", "Codigo": "Y34", "Descricao": "Análise de sangue (Dosagem de PSA)", "Categoria": "Genital masculino" },
    { "id": "98", "Codigo": "Y38", "Descricao": "Espermograma", "Categoria": "Genital masculino" },
    { "id": "99", "Codigo": "Y52", "Descricao": "Vasectomia / cauterização de lesões genitais", "Categoria": "Genital masculino" },
    { "id": "100", "Codigo": "Y67", "Descricao": "Encaminhamento para urologista", "Categoria": "Genital masculino" },
    { "id": "682", "Codigo": "Y70", "Descricao": "Sífilis masculina", "Categoria": "Genital masculino" },
    { "id": "683", "Codigo": "Y71", "Descricao": "Gonorreia masculina", "Categoria": "Genital masculino" },
    { "id": "684", "Codigo": "Y72", "Descricao": "Herpes genital", "Categoria": "Genital masculino" },
    { "id": "685", "Codigo": "Y73", "Descricao": "Prostatite / vesiculite seminal", "Categoria": "Genital masculino" },
    { "id": "686", "Codigo": "Y74", "Descricao": "Orquite / epididimite", "Categoria": "Genital masculino" },
    { "id": "687", "Codigo": "Y75", "Descricao": "Balanite / Balanopostite", "Categoria": "Genital masculino" },
    { "id": "688", "Codigo": "Y76", "Descricao": "Condiloma acuminado", "Categoria": "Genital masculino" },
    { "id": "689", "Codigo": "Y77", "Descricao": "Neoplasia maligna da próstata", "Categoria": "Genital masculino" },
    { "id": "690", "Codigo": "Y78", "Descricao": "Neoplasia maligna genital masculina, outra", "Categoria": "Genital masculino" },
    { "id": "691", "Codigo": "Y79", "Descricao": "Neoplasia benigna genital masculina NE", "Categoria": "Genital masculino" },
    { "id": "692", "Codigo": "Y80", "Descricao": "Traumatismo genital masculino, outro", "Categoria": "Genital masculino" },
    { "id": "693", "Codigo": "Y81", "Descricao": "Fimose / prepúcio redundante", "Categoria": "Genital masculino" },
    { "id": "694", "Codigo": "Y82", "Descricao": "Hipospádias", "Categoria": "Genital masculino" },
    { "id": "695", "Codigo": "Y83", "Descricao": "Testículo não descido / Criptorquidia / Testículo ectópico", "Categoria": "Genital masculino" },
    { "id": "696", "Codigo": "Y84", "Descricao": "Malformação genital congénita masculina, outra", "Categoria": "Genital masculino" },
    { "id": "697", "Codigo": "Y85", "Descricao": "Hipertrofia benigna da próstata / hiperplasia prostática benigna", "Categoria": "Genital masculino" },
    { "id": "698", "Codigo": "Y86", "Descricao": "Hidrocele", "Categoria": "Genital masculino" },
    { "id": "699", "Codigo": "Y99", "Descricao": "Doença genital masculina, outra", "Categoria": "Genital masculino" },

    // --- PROBLEMAS SOCIAIS ---
    { "id": "700", "Codigo": "Z01", "Descricao": "Pobreza / problemas económicos", "Categoria": "Problemas sociais" },
    { "id": "701", "Codigo": "Z02", "Descricao": "Problemas relacionados a água / alimentação", "Categoria": "Problemas sociais" },
    { "id": "702", "Codigo": "Z03", "Descricao": "Problemas de habitação / vizinhança", "Categoria": "Problemas sociais" },
    { "id": "703", "Codigo": "Z04", "Descricao": "Problema sócio-cultural", "Categoria": "Problemas sociais" },
    { "id": "704", "Codigo": "Z05", "Descricao": "Problemas com condições de trabalho", "Categoria": "Problemas sociais" },
    { "id": "705", "Codigo": "Z06", "Descricao": "Problemas de desemprego", "Categoria": "Problemas sociais" },
    { "id": "706", "Codigo": "Z07", "Descricao": "Problemas relacionados com educação", "Categoria": "Problemas sociais" },
    { "id": "707", "Codigo": "Z08", "Descricao": "Problema relacionado com sistema de segurança social", "Categoria": "Problemas sociais" },
    { "id": "708", "Codigo": "Z09", "Descricao": "Problema de ordem legal", "Categoria": "Problemas sociais" },
    { "id": "709", "Codigo": "Z10", "Descricao": "Problema relacionado com sistema de saúde", "Categoria": "Problemas sociais" },
    { "id": "710", "Codigo": "Z11", "Descricao": "Problema relacionado com estar doente", "Categoria": "Problemas sociais" },
    { "id": "711", "Codigo": "Z12", "Descricao": "Problema de relacionamento com parceiro / conjugal", "Categoria": "Problemas sociais" },
    { "id": "712", "Codigo": "Z13", "Descricao": "Problema comportamental do parceiro / companheiro", "Categoria": "Problemas sociais" },
    { "id": "713", "Codigo": "Z14", "Descricao": "Problema por doença do parceiro / companheiro", "Categoria": "Problemas sociais" },
    { "id": "714", "Codigo": "Z15", "Descricao": "Perda ou falecimento do parceiro / companheiro", "Categoria": "Problemas sociais" },
    { "id": "715", "Codigo": "Z16", "Descricao": "Problema de relacionamento com criança", "Categoria": "Problemas sociais" },
    { "id": "716", "Codigo": "Z18", "Descricao": "Problema com criança doente", "Categoria": "Problemas sociais" },
    { "id": "717", "Codigo": "Z19", "Descricao": "Perda ou falecimento de criança", "Categoria": "Problemas sociais" },
    { "id": "718", "Codigo": "Z20", "Descricao": "Problema de relacionamento com familiares", "Categoria": "Problemas sociais" },
    { "id": "719", "Codigo": "Z21", "Descricao": "Problema comportamental de familiar", "Categoria": "Problemas sociais" },
    { "id": "720", "Codigo": "Z22", "Descricao": "Problema por doença familiar", "Categoria": "Problemas sociais" },
    { "id": "721", "Codigo": "Z23", "Descricao": "Perda / falecimento de familiar", "Categoria": "Problemas sociais" },
    { "id": "722", "Codigo": "Z24", "Descricao": "Problema de relacionamento com amigos", "Categoria": "Problemas sociais" },
    { "id": "723", "Codigo": "Z25", "Descricao": "Ato ou acontecimento violento", "Categoria": "Problemas sociais" },
    { "id": "724", "Codigo": "Z27", "Descricao": "Medo de problema social", "Categoria": "Problemas sociais" },
    { "id": "725", "Codigo": "Z28", "Descricao": "Limitação funcional / incapacidade", "Categoria": "Problemas sociais" },
    { "id": "726", "Codigo": "Z29", "Descricao": "Problema social NE", "Categoria": "Problemas sociais" },
    { "id": "101", "Codigo": "Z45", "Descricao": "Aconselhamento sobre problemas sociais", "Categoria": "Problemas sociais" },
    { "id": "102", "Codigo": "Z58", "Descricao": "Escuta terapêutica para apoio social", "Categoria": "Problemas sociais" },
    { "id": "103", "Codigo": "Z62", "Descricao": "Procedimento administrativo social (Atestados, relatórios)", "Categoria": "Problemas sociais" },
    { "id": "104", "Codigo": "Z66", "Descricao": "Referenciado para assistente social ou órgãos de apoio", "Categoria": "Problemas sociais" }
];

var tbody = document.getElementById("tbody");

function create_elment(item) {
    return `
        <tr>
            <td><strong>${item.Codigo}</strong></td>
            <td>${item.Descricao}</td>
            <td><span class="badge-categoria">${item.Categoria}</span></td>
        </tr>
    `;
}

function load() {
    tbody.innerHTML = "";
    for (var i = 0; i < data.length; i++) {
        xuat(data[i]);
    }
    document.getElementById('number1').innerHTML = data.length;
    document.getElementById('number2').innerHTML = data.length;
}

function xuat(item) {
    var tr = document.createElement("tr");
    tr.innerHTML = create_elment(item);
    tbody.appendChild(tr);
}

// Inicializa a tabela carregando todos os dados
load();

// Lógica de pesquisa unificada em tempo real
var search = document.getElementById("search");
// Função auxiliar para remover acentos e padronizar textos para busca
function normalizarTexto(texto) {
    return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}

// Lógica de pesquisa aprimorada (ignora acentos e busca por múltiplas palavras)
var search = document.getElementById("search");
// Função auxiliar para remover acentos e padronizar textos para busca
function normalizarTexto(texto) {
    return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}

// Lógica de pesquisa aprimorada e tolerante
var search = document.getElementById("search");
// Função auxiliar para remover acentos e padronizar textos para busca
function normalizarTexto(texto) {
    return texto ? texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase() : "";
}

// Lógica de pesquisa unificada por Descrição e Categoria
var search = document.getElementById("search");
search.addEventListener("keyup", function () {
    var searchValue = normalizarTexto(search.value);
    tbody.innerHTML = "";
    
    if (searchValue.trim() === "") {
        load();
    } else {
        var matchCount = 0;
        var termosBusca = searchValue.split(/\s+/);

        for (var i = 0; i < data.length; i++) {
            var codigoNorm = normalizarTexto(data[i].Codigo);
            var descricaoNorm = normalizarTexto(data[i].Descricao);
            var categoriaNorm = normalizarTexto(data[i].Categoria);

            // Cada termo digitado deve aparecer ou no Código, ou na Descrição, ou na Categoria
            var atendeTodosOsTermos = termosBusca.every(function(termo) {
                // Tratamento básico para singular/plural (ex: "procedimento" encontra "Procedimentos")
                var termoSingular = termo.endsWith('s') ? termo.slice(0, -1) : termo;

                return codigoNorm.indexOf(termo) >= 0 || 
                       descricaoNorm.indexOf(termo) >= 0 || 
                       categoriaNorm.indexOf(termo) >= 0 ||
                       categoriaNorm.indexOf(termoSingular) >= 0;
            });

            if (atendeTodosOsTermos) {
                xuat(data[i]);
                matchCount++;
            }
        }
        document.getElementById('number1').innerHTML = matchCount;
        document.getElementById('number2').innerHTML = data.length;
    }
});
